### ISSUE TITLE
Sniffdog messes with MSI afterburner settings

### ISSUE THREAD

**Issue by jesse0032** [Sniffdog/Sniffdogminer#10]
I have three main rigs all running 1080ti's.  One of the rigs which is my main gaming PC and only has one card in.

The issue is the top card in MSI after burner will often have its settings reset to default even though it hasn't changed in MSI afterburner.  At least once or twice a day this will happen.

The only reason I know it is defaulting that one card is because the temperature goes from 60degrees to 84C which is the cut off for throttling at default settings.

I just apply the settings again and it works for a random amount of time.    Also I can hear it change as the fan goes from 80% to 40%.

I know this is 100% related to sniffdog.  Because while zpool and hash ref were down I havn't used it for 3 days or more and it has not had this problem even once.

I have this problem on a machine with 4 cards and a machine with 2 cards.

Another machine with 4 cards doesn't seem to be effected but it hasn't been without issues.

The machine I get the most issues on uses default bat file but I have cut the amount of algo's down to try and eliminate the bug.

 -Algorithm skein,blakecoin,Nist5,blake2s,blakecoin,keccak,veltore,MyriadGroestl  So far I have got down to this many but the bug still persists.

**Comment by Sniffdog** [comment]
Honest to goodness..it's not a sniffdog issue....This is a ccminer issue. Also, we don't use any program enhancement programs like "MSI Afterburner" with our rigs... you use those program at your own Risk because manufacturers soon won't warranty your system if they think your overclocking/underclocking your system!!!

**Comment by Sniffdog** [comment]
And yes using an enhancement programs may throw your card out due to "memory intensive" algos. Try to increase your virtual memory... or perhaps your power supply...  I had one guy switch over to sniffdog after running zcash and he had many issues... even had to update windows to 10 and let updates run. Also had to increase power supply and virtual memory, placed daily resets and pickup a wall plug to turn off in case of freezing. 

I will try turn off all pool stat requests  from ccminers in the next update.

**Comment by jesse0032** [comment]
I use CCminer all the time without sniffdog and this never happens.   I
also don't overclock.  I underpower my cards from 100% to 85% and crank the
fan speed up.   If you leave your cards at default they run about 20-30c
hotter and also waste a lot of power.

If it is a CCminer issue its one that only pops up when used with
Sniffdog.  Default settings overwork and undercool the cards.  Not really
sure how you are running it with default settings and it not overeheating.
When the card resets to defaults it goes from 55c to 84c.

I could use other methods to set the clocks but that would require
modifications to every algorithm to set the fan speed and power settings.

**Comment by Sniffdog** [comment]
just sounds like your card is cutting out and resetting...

I personally use -Delay 5 seconds for between algos and interval of 120 seconds for checking api

**Comment by jesse0032** [comment]
I will try increase the delay setting.  Thanks.  Also is there somewhere like a forum or something we can post about sniffdog?

**Comment by Sniffdog** [comment]
Not at this time due to my lack of time to monitor the forum

**Comment by frederikvanduuren** [comment]
interval of 120 seconds for checking api
i use 150...
did you ever benchmark this?
why 120?

**Comment by Sniffdog** [comment]
Actually, the default is 90. Really upto the user of this program. I start sniff at 90 to finish benching.... then switch interval (to what I think) is reasonable. Today I have one rig at 240 interval. It's all about preference

**Comment by frederikvanduuren** [comment]
90 seems to low, because each algo takes some time to startup...

Maybe we could write some sniffer that benchmarks the time of each reward/algo ? ;)
Its not about preferences, more about best practice...
regards
fred

**Comment by Sniffdog** [comment]
90 sec for each algo is to low? You do know how long it takes to bench the ever adding algos to sniff? No, I'll keep it at 90 thanks as a default. People can choose what to do with Sniff.

Sniff auto benches after but I also rebench once a week

**Comment by frederikvanduuren** [comment]
ahaa ok, but how do you explain your 240 on other rigs?
keep up the good work :)

**Comment by frederikvanduuren** [comment]
90 is ok, depending on what algos will be running... 
neoscrypt needs 5 seconds to startup
but sib needs 25 seconds to startup ...
this just means that of the 90 seconds its not mining 27% of its time...
so its all about ofsetting the cost of restarting a new algo vs the higher earnings of picking a new algo...

**Comment by Sniffdog** [comment]
No 90 second interval is just to map your initial benches. I use 240 because most miners are at half "hashing" by the pool stats

If that algo is still valid after 240 for another round at 240 then the miner is usually at full hash( at pool stats)

Just the way to think about it as well

**Comment by frederikvanduuren** [comment]
bro

i currently run it every 40 seconds... i did benchmark it with my other rigs & i get higher returns around 41 seconds... because the high rewards fall faster away i guess ;)

makes sense?!

fred

**Comment by Sniffdog** [comment]
Yes it makes sense cause that's the way you like it :)

Just like the way I like my settings :)
