### ISSUE TITLE
CcminerKlaust on version 4.1

### ISSUE THREAD

**Issue by btnottrue** [Sniffdog/Sniffdogminer#100]
Script cannot get Hashrate Speed from CcminerKlaust happen on both Groestl and NeoScrypt algo
causeing script keep benchmark loop for both algo

**Comment by kingyem** [comment]
the same happens with hashsynminer for GPU 0 (Nvidia), but for GPU 1 (Nvidia1) is working.

**Comment by swittmann** [comment]
Same here, Can't complete the bench because it never completes the hash. Went back to 3.9

**Comment by Sniffdog** [comment]
hmmm maybe I should hard bind 4068 to klaustT API port?

**Comment by Sniffdog** [comment]
-b 0.0.0.0:4068 fixed the issue in Hashsynminer in Klaust0...

I will place it into Klaust mine for SniffDog

Thank you for letting me know he turned off even his default port
