### ISSUE TITLE
Zergpool bad config -> no payout

### ISSUE THREAD

**Issue by zogo755** [Sniffdog/Sniffdogminer#101]
Zergpool has changed its command line config therefore there is no payout when using zergpool as current sniffdog version use u="BTC address'  instead of c="BTC address"

23.01.2018 We have introduced changed to parameter configuration we pass to stratum in command line.
c=SYMBOL will stand for payout wallet identification, mc=SYMBOL will stand for mining coin identification.
Final password string should look like c=SYMBOL,mc=SYMBOL for Option 2 and 3. And for Option 1 it will be c=SYMBOL only.
Will roll out changes 20:00 CET time for all stratums.

**Comment by Sniffdog** [comment]
From Zergpool front page...


-o stratum+tcp://zergpool.com:PORT -u <YOUR_BTC_ADDRESS> -p c=BTC

As you will see we do use this address for sniffDog which is universal with all pools 

As far as not getting many mined coins... this is a new pool so if your not happy you can remove it from your startsniffin.bat file

**Comment by zogo755** [comment]
I see, I had no earning at all despite mining several hours with zergpool so I thought it was config related especially after  I saw the update I paste from zergpool, but you are right that config work now, probably somee glinch with ergpool that have been fixed. Sorry for the wrong issue!

By the way would you consider adding altminer.net ? no auto autoexchange yet but a good pool

**Comment by Sniffdog** [comment]
nah just need more hashing there to mint more coins. compare with other pools and you will see

**Comment by zogo755** [comment]
I agree but got better result for some coins like LUX using altminer than other pools

**Comment by Sniffdog** [comment]
Yeah... I think the enviroment will get better over also solo mining a coin at Zerpool once they have more users multi mining
