### ISSUE TITLE
Poor results

### ISSUE THREAD

**Issue by seanklei10** [Sniffdog/Sniffdogminer#102]
As I watch the miner I'm consistently seeing >$30/day estimate (for 2x 1080ti's) however, I've only been consistently getting ~$15/day. I've removed some of the algo's that appear to be very unstable (will jump to $40 one time, then $2 the next) as well as tried changing from 90seconds to 300seconds to 600seconds. Anything else I may be doing wrong?

**Comment by Sniffdog** [comment]
I'm Sorry @seanklei10 but that just the way the API for each pool reads.... and if your getting $15 a day then I'm kinda impressed with two cards roughly $7.50 per card estimating over 30 days is $450 dollars.... wow wouldn't be long before you paid off those cards if bitcoin stays at this price.... 

$450x12months is $5,400 dollars

... just from 2 cards....

**Comment by seanklei10** [comment]
They are certainly not bad results, was just curious if anyone had found a better way to optimize for 1080ti's.

**Comment by Sniffdog** [comment]
We are certainly trying our best here at Sniffdog to make everyone increase hash by providing updates that are suitable to Nvidia mining

**Comment by seanklei10** [comment]
I certainly appreciate all of your work and I'm am very interested to work with this community to make it better for everyone. Are the differences between hashsynminer and sniffdogminer just the ability to change more/less settings or are there other differences?

**Comment by Sniffdog** [comment]
Hashsynminer can be used for splitting a rig with a buddy or two...(tested to 6 different bitcoin addresses)

**Comment by romajc84** [comment]
$7.50/card is really good right now.
