### ISSUE TITLE
Rename error for Ccminer_x86_krnlx

### ISSUE THREAD

**Issue by GuyTechie** [Sniffdog/Sniffdogminer#104]
Getting this:
Rename-Item : Source and destination path must be different.
At F:\Miners\Sniffdogminer-master-4.1\Include.ps1:534 char:5
+     Rename-Item "$(Split-Path $Path)\$FolderName_Old" "$FolderName_Ne ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (F:\Miners\Sniff...miner_x86_krnlx:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand

**Comment by Sniffdog** [comment]
if you just added the link to the miners folder... you will see I also changed the directory... and the miner has a different name

**Comment by GuyTechie** [comment]
FYI, I add anything.  I did notice the name change in your path, however.  Still not sure why it would cause that message.  I thought maybe you missed something in the script because of this slight difference.

**Comment by Sniffdog** [comment]
I'll test today

**Comment by Sniffdog** [comment]
Ahh I see what your saying now... all good

If you have old zip or rare files in the of the other palgin you need to remove those
