### ISSUE TITLE
Created a 3 GPU monitor batch file.  Please add if you can.

### ISSUE THREAD

**Issue by GuyTechie** [Sniffdog/Sniffdogminer#106]
I would love to look and see if I can create a dynamic of variable for this batch file.  If there's no way to automatically detect the number of cards, maybe ask the user how many cards on first run and store the value in a file for subsequent use.

For now, I needed a 3 GPU monitor, so I edited the existing one.  For those who also need a 3 GPU monitoring batch file:

[Monitor_3card.zip](https://github.com/Sniffdog/Sniffdogminer/files/1670561/Monitor_3card.zip)

**Comment by GuyTechie** [comment]
Oh, before you do, I made a minor change.  Replace the GTR 40 with GTR 70.  This way, if a single card fails, it would still detect as a failure and reboot.  A single card dying is 66.66% GPU usage, so would still be considered "Mining is working" if it was set to detect at 40.  :-/

**Comment by Sniffdog** [comment]
The old Alexis Ccminer (from previous versions) can take upto a minute to get all cards running after 4

Will having this cause the miner to reboot at GTR 70?

**Comment by GuyTechie** [comment]
Maybe increase the check wait time.  The first one is 60 seconds.  The subsequent checks are 30 seconds.

I wrote this for my 3 card rig because sometimes a single GPU would stop working and only a reboot would fix it.  Finally have this to help automate the process.

I also wrote and used a batch file to check for internet connectivity (is a WIFI rig), and would reboot if it loses connectivity.  Since this batch file does that as well, I discontinued the use of my own batch file.

Automation is nice, no?

**Comment by Sniffdog** [comment]
I agree it is nice... I'll just double check that on a rig I have here that is 6 cards to see if the updated Alexis will work at GTR 40 and I'll what you just wrote to the readme file as well

**Comment by GuyTechie** [comment]
Thanks.

Also, another change - REM out these lines if you don't use nircmd.exe to take screenshot for logs.  This also prevents the creation of the Scr folder that's unneeded.

Oh, and I didn't realize to fix the id^x numbering until just now.

`rem SET scrpath=%mypath%Scr
rem if not exist "%scrpath%" mkdir "%scrpath%"

rem "%mypath%nircmd.exe" savescreenshot "%scrpath%\%TIME:~0,-9%-%TIME:~3,2%-%TIME:~6,2%.png"
rem echo "%scrpath%%DATE:~6,4%.%DATE:~3,2%.%DATE:~0,2% %TIME:~0,-9%-%TIME:~3,2%-%TIME:~6,2%.png"`

I guess I should just repost a new file instead.  Sorry for all these little iterations.  It's what we do, no?

If you find it's a good idea to adjust the GPU utilization to detect a single card failure, remember to apply the changes to the other batch files as well (eg, for 8 rig card, you'll need to detect utilization at around 90%), or lower if you just want to only reboot if more cards quits mining in a larger rig before considering a failure.
[Monitor_3card.zip](https://github.com/Sniffdog/Sniffdogminer/files/1670619/Monitor_3card.zip)

**Comment by Sniffdog** [comment]
Haha yes it can be but lately I have been using Ethmonitor (paid 2 bucks a month and accepts bitcoin) and slap it in the background... it would be nice just to give the users something free to keep their mining going through the night or maybe through a holiday if needed
