### ISSUE TITLE
Lyra2re2 keeps showing high usd/day

### ISSUE THREAD

**Issue by romajc84** [Sniffdog/Sniffdogminer#109]
6 x 1080 Ti and it shows 850$/day

I deleted the stats and it fixed it for a while but now it is back.

Not happening on my 1 x 1080 Ti gaming pc.

**Comment by Sniffdog** [comment]
which pool? and if it was fixed then did it again after hashing for days... usually means its an exchange api ( pools requirement) and will fix itself

But yeah which pool is it or is it all the pools with lyra2rev2

**Comment by romajc84** [comment]
it is ahashpool.

I was just deleting the ahashpool lyra2rev2 single script.

**Comment by Sniffdog** [comment]
Yeah that's either API from an exchange the pool uses to the pool operator working in the background
