### ISSUE TITLE
Incorrectly reported hashrate bug?

### ISSUE THREAD

**Issue by strosz** [Sniffdog/Sniffdogminer#11]
Hi, first I want to thank you for the great miner!

Though, yesterday a strange problem started on a rig with 5x identical 1070GTX.

The sniffdog window started showing 500-1000USD/day for Lyra2RE2 on zpool. Which made the miner only mine that and nothing else. It's of course wrong though. And after a while of mining it, it even started to show 'an invalid memory access...' something in the ccminer window. 

Also now saw it happen on another rig with different hardware that's completely stable. Seems like it confuses GH with MH perhaps. Since the Sniffdog window showed Lyra2RE2 hashrate as over 15GH/s which sounds a lot. Can't explain the memory access error on the first rig though, since all other algos works perfectly.

**Comment by Sniffdog** [comment]
well it might be a palgin issue... just go into the miners folder and choose another ccminer by removing the # in front of lyra2RE2 then add a # to palgin lyra2RE2

Hopefully this helps you... I do re bench weekly on my personal rig just to reset... the benchmarks are dynamic for sniffdog so...over time... they will reset auto

**Comment by strosz** [comment]
Thanks, I changed the miner to CcminerTpruvot for Lyra2RE2 and it passed the benchmark. Also tried CcminerAlexis, but that one threw the same invalid memory errors before the benchmark could finish.

Good to know how to change miners for every algo.

Will update if the issue returns.
