### ISSUE TITLE
Is verry nice Miner

### ISSUE THREAD

**Issue by Klein80** [Sniffdog/Sniffdogminer#112]
Please add Nicehash in this Miner?
Thank you for your work +1:

**Comment by Sniffdog** [comment]
I'm still up in the air about nicehash and their 5% fee's.... im pretty sure ahashpool has better results and at 1% and zergpool at 0% (if zergpool can show they are ready for the Big Time)

**Comment by btnottrue** [comment]
agree with @Sniffdog nicehash fee is too high compare to ahashpool
you can make equal or even more on these pool
