### ISSUE TITLE
Location no EU?

### ISSUE THREAD

**Issue by Klein80** [Sniffdog/Sniffdogminer#113]
Hello,

this Programm/Script is Location US.
I change Location EU not working. 

Is not fine for hash speed US Location for me (EU Country).
RIght?

**Comment by Sniffdog** [comment]
yeah Europe... I'll change that today

stratum difficulty to high at Zergpool for gpu...to meet with nicehash recomendations

**Comment by Klein80** [comment]
Nice + thank you verry mutch, i wait to can make EU change to Location in Bat File...

:1st_place_medal:

**Comment by Sniffdog** [comment]
you can download master copy if you want to start right now(just not release) and you have to put in Europe(not EU)

**Comment by Klein80** [comment]
Is really nice Miner, i have test more Miners - this are stabil and fine. 

We work this time with 8 x 1080 ti and 5x 1070 ti for testt it.

Europe not working - Benachmark first 2 Miners are ok 3.-4. say... "....:80 Port.."
Thank you for your create this Script.

:)

**Comment by Klein80** [comment]
What you thik - Final release to SniffDogMiner  with EU Option?

+ what is best time for Switch?
2 min? (Problem is x17 algo have minimum self 1.5 min to speed max.)

Thank you

**Comment by Sniffdog** [comment]
https://github.com/Sniffdog/Sniffdogminer

download SniffDog from here and your more than welcome to increase interval if you like
