### ISSUE TITLE
Mining rig restarting

### ISSUE THREAD

**Issue by abinsraj** [Sniffdog/Sniffdogminer#116]
Hi,
I'm using Sniffdogminer flalessly for a month using Sniffdogminer-2.8.A. But 2 days back my rig restart whenever I run sniffdog. I'm mining x17,sib,xevan,Nist5,blake2s,skein algorithms on ahashpool. I tried installing and uninstalling old and new drivers, & also tried new sniffdog release.  Please help I need your assistance.

**Comment by Sniffdog** [comment]
with new sniffdog you need the latest drivers....

I have a feeling that if your starting to have problems you better check your hardware

how big is your miner?

**Comment by abinsraj** [comment]
I'm using 2x1080ti and 2x1060 (6gb)

**Comment by abinsraj** [comment]
I'm getting below error when i start sniffdog

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Sniffdogminer-2.8.A\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Sniffdogminer-2.8.A\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Sniffdogminer-2.8.A\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Sniffdogminer-2.8.A\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~

**Comment by abinsraj** [comment]
@Sniffdog should I reinstall windows?

**Comment by abinsraj** [comment]
@Klein80 

1. I will create the folder in desktop
2. 40 -45 gb
3. How to install cuda 9.1?
4. Yup new driver.
5. yes deactive.

**Comment by abinsraj** [comment]
Another error


ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by Sniffdog** [comment]
also erase your profit stats in sniffdog... that error is sometimes a corrupt file

**Comment by Klein80** [comment]
Next Time make copy your Folder... 
so you can delete error Folder + start with Copy Folder.

**Comment by Sniffdog** [comment]
i left a profit remover in latest sniffdog... you shouldn't have needed to delete the whole stats folder... and logs I could place a bat file to remove logs instead of manually doing it

**Comment by erikpar** [comment]
i tried it all and my rig get restart once i start the benchmark

**Comment by Sniffdog** [comment]
yeah I'm surprised you can get 2.8 started... some users are mentioning the download links are not working

**Comment by kodeballer** [comment]
moved a few things around and think it was due wattage use from my PSU, i moved some things to other circuit breaker outlets and no resets since..(past the 3-4 hour mark as of this post)

**Comment by kelib99** [comment]
Same problem here. I got 2 rigs: 
1x MSI 1080ti, 2x Evga 1070ti, 1x Gigabyte 1070ti, 1300 w psu, Evga Precision tool (cca 80%, +100, +400)
6x MSI 1070, 1000 w + 620 w psu,  MSI Afterburner, 80%, +100, +400.
First rig works perfectly without an issue. 

The second rig was restarting when benchmarking some algos. 
After disabling the Afterburner, it seems like it works correctly. Later, i will try with Evga precision tool.
