### ISSUE TITLE
Adding pools

### ISSUE THREAD

**Issue by chillout37** [Sniffdog/Sniffdogminer#117]
Hi how easy is it to add additional pools in such as yimp and antpool
excellent work so far

**Comment by Sniffdog** [comment]
never thought of it as of yet... been over at zergpool helping out with issues lately... glad to see more multiminers adding zergpool

We could keep this as a "to do" for later... right now my next goal is to get a litecoinstart.bat file going for SniffDog so everything auto converts to litecoin

**Comment by chillout37** [comment]
cool i have seen u in the zerg chat litecoin sounds good  appreciate it
