### ISSUE TITLE
run command is empty

### ISSUE THREAD

**Issue by erikpar** [Sniffdog/Sniffdogminer#118]
0.00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\NVIDIA-Poly\ccminer.exe -a poly -o stratum+tcp://: -u  -p

**Comment by erikpar** [comment]
Loading BTC rate from 'api.coinbase.com'..
Last Refresh: 02/04/2018 15:10:39
1BTC =  8767.7 USD

PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."
PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."
PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."
PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."

   Type: NVIDIA

Miner           Algorithm            Speed      BTC/Day BTC/GH/Day      USD/Day Pool
-----           ---------            -----      ------- ----------      ------- ----
CcminerTpruvot  Lyra2z           5.74 MH/s      0.00113    0.19765        9.947 zergpool-2-coin(s)
CcminerKlaust   NeoScrypt        2.90 MH/s      0.00102    0.35138        8.929 zergpool-20-coin(s)
CcminerTpruvot  Bitcore         46.80 MH/s      0.00087    0.01864        7.648 zergpool-1-coin(s)
CcminerTpruvot  Phi           Benchmarking Benchmarking    0.00780 Benchmarking zergpool-1-coin(s)
CcminerKlaust   Groestl       Benchmarking Benchmarking    0.00300 Benchmarking zergpool-1-coin(s)
CcminerPoly     Polytimos     Benchmarking Benchmarking            Benchmarking -
Duel_Ethash_Sia Ethash        Benchmarking Benchmarking    0.00903 Benchmarking MPH-Ethereum
EWBF            Equihash      Benchmarking Benchmarking  659.78000 Benchmarking zergpool-5-coin(s)
hsrminer        NeoScrypt     Benchmarking Benchmarking    0.35138 Benchmarking zergpool-20-coin(s)
CcminerTpruvot  Skunk         Benchmarking Benchmarking    0.00880 Benchmarking zergpool-1-coin(s)
CcminerTpruvot  Timetravel    Benchmarking Benchmarking            Benchmarking -
CcminerTpruvot  Tribus        Benchmarking Benchmarking    0.00775 Benchmarking zergpool-2-coin(s)
Ccmineralexis   X17           Benchmarking Benchmarking    0.03236 Benchmarking zergpool-2-coin(s)
Ccmineralexis   C11           Benchmarking Benchmarking    0.01332 Benchmarking zergpool-3-coin(s)
Ccmineralexis   Hsr           Benchmarking Benchmarking    0.02192 Benchmarking zergpool-1-coin(s)
Ccmineralexis   Keccak        Benchmarking Benchmarking    0.00016 Benchmarking MPH-Maxcoin
Ccminer-krnlx   Xevan         Benchmarking Benchmarking    0.08514 Benchmarking zergpool-5-coin(s)
Ccmineralexis   Blake2s       Benchmarking Benchmarking    0.00010 Benchmarking zergpool-4-coin(s)
Ccmineralexis   Blakecoin     Benchmarking Benchmarking            Benchmarking -
Ccmineralexis   Sib           Benchmarking Benchmarking    0.01193 Benchmarking zergpool-1-coin(s)
Ccmineralexis   Skein         Benchmarking Benchmarking    0.00042 Benchmarking zergpool-5-coin(s)
Ccmineralexis   X11evo        Benchmarking Benchmarking            Benchmarking -
Ccmineralexis   Lyra2RE2      Benchmarking Benchmarking    0.00712 Benchmarking MPH-Monacoin
Ccmineralexis   MyriadGroestl Benchmarking Benchmarking    0.00024 Benchmarking MPH-DigibyteGroestl
Ccmineralexis   Nist5         Benchmarking Benchmarking    0.00781 Benchmarking zergpool-2-coin(s)




   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-Poly\ccminer.exe -a poly -o stratum+tcp://: -u  -p

**Comment by Sniffdog** [comment]
means Sniffdog didn't pickup API... is it working now?

**Comment by erikpar** [comment]
still the same

**Comment by erikpar** [comment]
Downloaded clean master and now the command is not empty but failed on benchmark 
rig crash when benchmark:
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-TPruvot\ccminer.exe -a bitcore -o stratum+tcp://zergpool.com:3556 -u 15prswGonSnXmfc98h69EY1DzVBL8uwSu1 -p ID=Sniffdog001,c=BTC --api-remote --api-allow=0/0

**Comment by erikpar** [comment]
after the crash it finish this and move to 
CcminerTpruvot  Phi           Benchmarking Benchmarking    0.04129 Benchmarking zergpool-1-coin(s)
now see this 
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-Poly\ccminer.exe -a poly -o stratum+tcp://: -u  -p

**Comment by Sniffdog** [comment]
that's is because poly is not at zergpool... I just made a startsniffinZergpool.bat file in sniffdog master for you

**Comment by erikpar** [comment]
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-TPruvot\ccminer.exe -a phi -o stratum+tcp://: -u  -p  -i 23 --api-remote --api-allow=0/0

**Comment by Sniffdog** [comment]
yeah zergpool knows that tomorrow phi/lux will be updating their wallet so for now it's not at zergpool but will be soon
