### ISSUE TITLE
Specif 1080 ti?

### ISSUE THREAD

**Issue by succhiabello** [Sniffdog/Sniffdogminer#119]
First of all thanks for this amazing miner.
I was wondering why it says it's specific for 1080ti? I am using it with mixed 1080 1070 and 1080 tis. Am I doing it wrong or losing some profits?
Thanks and waiting for next release with Europe country region.
Ps been mining with 600 delay

**Comment by Sniffdog** [comment]
no your fine...what we use is 1080ti... if it's working for you then fantastic!
