### ISSUE TITLE
Possible to use other versions of Ccminer?

### ISSUE THREAD

**Issue by bitnoob1234** [Sniffdog/Sniffdogminer#12]
Just for lyra2z, some pools like MPH are reporting:
 '' Please update to djm34 ccminer release if you are mining Zcoin with NVIDIA GPU. Miner download link is posted at Zcoin pool ''

I tryed this with x86 and x64 versions just replacing and renaming it like the original used for this algo in Sniffdog(tpruvot) and it failed to launch. 

Any way to use other miners than included?
Thanks in advise

**Comment by bitnoob1234** [comment]
Edit: just found 1 version that worked

**Comment by bitnoob1234** [comment]
I worried that was fake news, now the miner crashes 1sec after started. So any way to use other miners in Sniffdog?

**Comment by Sniffdog** [comment]
Yes I am on holidays right now

**Comment by bitnoob1234** [comment]
ooh in that case just enjoy dude :)

**Comment by Sniffdog** [comment]
Lyra2z... tried djm34 ccminer and file was empy... switched to ccminer Tpruvot2.1
