### ISSUE TITLE
Lyra2RE2e - Zergpool does not exist

### ISSUE THREAD

**Issue by pike1181** [Sniffdog/Sniffdogminer#120]
Lyra2RE2e in ZergPool no longer exists on their page.
Miner bench marked a hashrate but when mining this algorithm returns 0/0
Not listed as an algorithm on their page either.
Not sure if something changed on their end or if there was a slip in the miners script.
Thanks!

**Comment by Sniffdog** [comment]
nah zergpool noticed an indifference in the exchange so he shut down the auto exchange.... auto exchange is back online

**Comment by pike1181** [comment]
Thanks!
