### ISSUE TITLE
Help with error code.

### ISSUE THREAD

**Issue by romajc84** [Sniffdog/Sniffdogminer#122]
Keep getting this error....

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\Joey\Desktop\Sniffdogminer-Rig2\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by Sniffdog** [comment]
remove profit and remove logs

**Comment by romajc84** [comment]
I just did that.  I also updated to the latest sniffdog and only copied over the stats folder.

Everything seems to be working fine but I am still getting that error.

**Comment by Sniffdog** [comment]
yeah i'm looking at a few other multiminer bitcointalk threads... it could be the api
