### ISSUE TITLE
Error SniffDog.ps1 :  MissingEndCurlyBrace

### ISSUE THREAD

**Issue by silimaure777** [Sniffdog/Sniffdogminer#123]
Everytime I try to start sniffdog miner I got this error : 

Au caractère C:\Users\kevra\OneDrive\Bureau\Sniffdogminer-master\SniffDog.ps1:78 : 1
+ {
+ ~
Accolade fermante « } » manquante dans le bloc d'instruction ou définition du type manquante.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

Anyone can help with this? I've tried to redownload the files multiple time and nothing to do.

**Comment by Sniffdog** [comment]
repaired and back on releases thank you
