### ISSUE TITLE
Splitting the rig in two?

### ISSUE THREAD

**Issue by Nickduino** [Sniffdog/Sniffdogminer#124]
I have 12 x 1080 Ti, I'd like half of them to mine to an account (ideally ETH, not BTC) and the other half to another wallet. Is it possible to edit startsniffin.bat in such a way?

Or run two Sniffdogminers with two sets of miners on the same rig?

**Comment by Nickduino** [comment]
Oh, that's what [SplitSniff](https://github.com/Sniffdog/SplitSniff) is for, isn't it!?

**Comment by Sniffdog** [comment]
yes but use hashsynminer instead of splitsniff

updated

**Comment by Nickduino** [comment]
Is [Hashsynminer](https://github.com/Sniffdog/Hashsynminer) different from what SplitSniff achieves (was supposed to achieve)?


Powerhog, you mean......CPU-wise? Would a G4400 manage two accounts?

**Comment by Sniffdog** [comment]
well just keep monitoring it for a day and see...

Hashsynminer is better and with all new miners

you can run a dedicated seperate lane for the other account that's ported

**Comment by Nickduino** [comment]
I'll install it from the github master as soon as I have my 1080 Ti rig up and running (hope to get the last parts by saturday but it could be next week).


> you can run a dedicated seperate lane for the other account that's ported
Sorry, what?
(What's a lane, what's a **ported** account)

**Comment by Sniffdog** [comment]
i ported it so it won't screw the benchmarks up running two accounts... if you had everything running on the same port the benches would change drastically.....

If you have problems just ask for help in hashsynminer issues
