### ISSUE TITLE
v4.4 CPUminer does not launch

### ISSUE THREAD

**Issue by chillware** [Sniffdog/Sniffdogminer#125]
Window for CPUminer pops up and closes immediately. Tried running from command line w/ correct options and cpuminer-avx2.exe just quits w/o any warnings or errors.

**Comment by chillware** [comment]
Folder already has all .dll files..

**Comment by Sniffdog** [comment]
good and did you see the readme?

**Comment by chillware** [comment]
Yes, I ensured I launched the correct exe for my CPU (avx2)

.. just checked github for jayddee, looks like a fixed avx2 binary was released an hour ago.. I will try the updated binary and follow up.

**Comment by GuyTechie** [comment]
Looks like cpuminer-opt has a bug in 3.8.1.  The dev just released 3.8.1.1 to fix it.  Someone reported an issue with neoscrypt still, but we don't use it for neoscrypt so we should be ok.

**Comment by Sniffdog** [comment]
I just updated files in Sniffdog
