### ISSUE TITLE
Select  GPUs individually

### ISSUE THREAD

**Issue by tatsumakisen** [Sniffdog/Sniffdogminer#126]
My Rig configuration is:

7  GTX 1080ti
1 GTX 1070

8 GPU total

I love Sniffdogminer, but the only problem is sometimes doesn't run the 8 GPU   only 7 ....
then i have to restart the system and run Sniffdogminer again

the question is.. 

Can I select the GPUs individually ? I mean  0,1,2,3,4,5,6,7

also,  What is the best interval  to use for ahashpool with all algo ???

thanks

**Comment by Sniffdog** [comment]
only program i have right now for that is hashsynminer... ported

it can be a resource hog..... 

use the monitor_8card in the Monitor folder... then when your card goes down you can check the error log as to why it's happening

**Comment by tatsumakisen** [comment]
Thanks so much!!
Appreciated

**Comment by tatsumakisen** [comment]
What overclock setting using MSI afterburner do you recommends ?

**Comment by Sniffdog** [comment]
i don't use overclock.. sorry..
