### ISSUE TITLE
Trojan:Win32/Vigorf.A  on 4.5 release

### ISSUE THREAD

**Issue by shhyguuy** [Sniffdog/Sniffdogminer#127]
I'm getting a Trojan alert on v4.5 from Windows Defender. Never happened for any other release version.
"Trojan:Win32/Vigorf.A"

**Comment by kingyem** [comment]
as for me, Windows Defender detected 
Trojan:Win32/ScarletFlash.A and Trojan:Win32/CoinMiner!bit
from the Ethash-Claymore miners

**Comment by kingyem** [comment]
after googling, apparently its a false positive

[https://www.reddit.com/r/EtherMining/comments/6hcw2h/trojan_lurking_in_claymore_dual_miner/](url)
[https://github.com/nanopool/Claymore-Dual-Miner/issues/54](url)

**Comment by Sniffdog** [comment]
damn claymore...

I will probably have to remove or use older version....
