### ISSUE TITLE
Adding Lyra2z, Timetravel, and Cryptonight to CPU mining

### ISSUE THREAD

**Issue by GuyTechie** [Sniffdog/Sniffdogminer#129]
There are more profitable coins to mine on CPU besides the ones you've currently enabled, according to your API sniffing script. 

I enabled all of the algos that JayDDee's CPU miner can mine and tested it out for a few weeks now.  Here's my findings:

Your default algos for CPU mining puts Yescript at the top most of the time, but after enabling other coins, Lyra2z comes up on top more than half the time.  Cryptonight comes in 3rd, but will need you to use cpu-affinity to get the best performance on Ryzen CPUs.  I haven't tested on Intel CPUs, but I'd expect that simply halving the threads work best for Intel CPUs with HT.

Timetravel comes in 4th place, but better than Xevan in the profitability contest. 

My current list goes:
Lyra2z
Yescrypt
Cryptonight
M7m
Timetravel
X17 - needs a very fast CPU, so may not be practical to enable by default
Bitcore
Xevan
X11evo - needs a very fast CPU, so may not be practical to enable by default

Can you enable these coins by default?  Here's my settings, if that helps:
"bitcore" = ",d=0.02"
"cryptonight" = " -t 16 --cpu-affinity 0x5555"  # Threadripper 1950X
"lyra2z" = ",d=5" # Difficulty might be ignored - more testing needed.
"timetravel" = ",d=0.5"

For CPU detecting and populating the right settings, you can probably use this in your script:
http://web.inter.nl.net/hcc/J.Steunebrink/chkcpu.htm

I used it to detect the CPU and choose the correct optimized cpu-miner before I started using Nemosminer and Sniffdogg.

If I have time, I can see if I can script something out, but not right now.

**Comment by Sniffdog** [comment]
Yes I will add very shortly.... 

Thank you so much!

**Comment by GuyTechie** [comment]
yes, actually cpuminer-avx2-sha.exe.

BTW, what does this mean?

SniffDog sniffs 0% and upto 43% more profit than the fastest (listed) miner:

Miner                             USD
-----                             ---
Sniffdog.. sniffs out!            16.97692 ±47% (11.55138-24.95076)
{Ccminer-krnlx-, JayDDeecpuavx2-} 13.98225 ±0% (13.98225-13.98225)

**Comment by Sniffdog** [comment]
it's a variance checker... not many miners know that pool profits and pool luck can fluctuates wildly.

Also, can be an indicator of when profits are starting to drop off from that algo... you will see more yellow

**Comment by Sniffdog** [comment]
Ok... your file is uploaded into Master copy 

Also added yescryptr16 Yenten to your list (zergpool added)

Enjoy!

**Comment by GuyTechie** [comment]
Excellent, thanks!

PS: Found out I could get away with getting rid of the difficultly setting for Lyra2z.  I originally based it on MPH, but I found out zerg and zpool can go lower, so it's better to just leave the diff setting out and let the pool sort it out.

**Comment by Sniffdog** [comment]
ok done

**Comment by Sharmway** [comment]
Hi, is there a way i can tweak algos, pools, so i get less yellow in the variance info ? If i enable all polls/algos, still getting the info about 10-40% more profitable choices. 
Another thin is,  how can i find out, which is the better algo/pool ? Info only states there is one...

**Comment by Sniffdog** [comment]
that all depends on how many rigs you have... if you have a lot rigs you can choose which pool you want to test and not be caught to long staying there if it wasn't the right choice

I understand what you are saying...... it's not easy....

You can see at different multiminers bitcointalk threads number and results relating to different pools but always remember... those numbers are drawn from past profit and can never be used to predict the future...

**Comment by Sharmway** [comment]
Is it possible to screeb the info of which pool/algo gives the yellow results?

**Comment by Sniffdog** [comment]
yellow results are from price variance of the miners.... if you have several pools open.....sniffdog checks for the highest price and luck before choosing that miner...
