### ISSUE TITLE
Request : Showing BTC/day value which has pool fee included

### ISSUE THREAD

**Issue by kingyem** [Sniffdog/Sniffdogminer#131]
Was wondering if you can implement this into your code?

https://github.com/nemosminer/NemosMiner-v2.4.2/issues/248

> In the pool file, I added *(1-($zergpool_Request.$_.fees/100)) after (both) divisor operations when setting the stat var:
**before (ahashpool):**
28:    if ((Get-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit") -eq $null) {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_last24h / $Divisor)}
29:    else {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_current / $Divisor)}
**after:**
28:    if ((Get-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit") -eq $null) {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_last24h / $Divisor *(1-($ahashpool_Request.$_.fees/100)))}
29:    else {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_current / $Divisor *(1-($ahashpool_Request.$_.fees/100)))}

**Comment by Sniffdog** [comment]
yes but how do we fix zpool with a variant on pool fees?

**Comment by nemosminer** [comment]
just add 2%

**Comment by Sniffdog** [comment]
you can't nemo... there are variants to zpool

Also this pool https://minemoney.com also has variants if we decide to add

**Comment by kingyem** [comment]
Ah I understand, that means there is no simplified way to fetch each fee for all pools? And if a constant fee is used for a particular pool with varying fees, this feature would not achieve what it was intended for right?

**Comment by kingyem** [comment]
Oh it's already included in the API? Ah didn't know that.

**Comment by Sniffdog** [comment]
yeah so I will see if we can fetch the fees directly from api and I'll check all api's and see if they have this

**Comment by Sniffdog** [comment]
ok all done and going to upload...

luckily, either by chance or knew what he was doing..... the divisor were set correctly...

Adding Fees as a Stat and will be uploading soon...

**Comment by Sniffdog** [comment]
![screenshot 104](https://user-images.githubusercontent.com/30452757/36135116-46abdda4-1046-11e8-8109-a4b75bbcda5c.png)
