### ISSUE TITLE
Mining Pool Hub with Claymore 11 for dual mining with keckak

### ISSUE THREAD

**Issue by kitty33421** [Sniffdog/Sniffdogminer#132]
Please help for dual mining both ETH & Keckak on claymore 11

**Comment by Sniffdog** [comment]
i did but it was flagged by defender as a virus so we downgraded

**Comment by kitty33421** [comment]
I know this flag but before you downgrade I try claymore 11 with sniffdog. On that time I can't mine ETH with Keckak together so I think because the ps file dosen't has MPH-Keckak pool server

**Comment by Sniffdog** [comment]
yes your right... the drawback was is that Claymore 11 had keccak and blake2s

the problem was it was flagged as a virus....

Sniffdog don't like flags and Claymore was made as just a Ethash(single)

**Comment by kitty33421** [comment]
Ok I see, thank you for your appreciation. ^-^
