### ISSUE TITLE
Please add support for Bminer

### ISSUE THREAD

**Issue by jrafaelmdo** [Sniffdog/Sniffdogminer#134]
Would love to have this one added as it seems to possibly be the fastest for equihash right now.

https://bitcointalk.org/index.php?topic=2519271.0

Thanks

**Comment by kingyem** [comment]
https://github.com/Sniffdog/Sniffdogminer/issues/111

Bminer had some bad feedbacks

**Comment by Sniffdog** [comment]
yeah right now it is but we are still looking for solutions

**Comment by ricoviq** [comment]
I'd like to see bminer too, most stable and fastest from what I've seen.

**Comment by Sniffdog** [comment]
i know but code will be needed to add Bminer... 

I will work on it.....

**Comment by Sniffdog** [comment]
Only support I added right now for Bminer is a solo miner batch file along with all the bells and whistles for solo mining.....

It is now in SniffDog under SoloMining Folder

As well as a solo miner for CCminer 

Instructions are included
