### ISSUE TITLE
Sniffdogminer 4.8 with 2 GPUs crashing on benchmark phase 

### ISSUE THREAD

**Issue by Mikeyjay73** [Sniffdog/Sniffdogminer#135]
Hey all,

I've been using SDM for a while on Zergpool with my Acer predator + 1080 a while and been pretty happy with it.

However, now after having installed a second GPU, 750Ti and installed fresh SDM 4.8, the benchmark does two first coins but crashes on phi. Removing phi from the algos list doesn't help since it's the same thing with the next coin,

Nicehash excavator seems to be working with this setup but I'd really like to stick with Zergpool and SDM.

Any ideas I could try?

**Comment by Sniffdog** [comment]
Sorry......... but I haven't made a 4.8 yet?

**Comment by Mikeyjay73** [comment]
It's the Zergpool fork version.

I can mine only the below algos:

 Type: NVIDIA

Miner          Algorithm      Speed BTC/Day BTC/GH/Day EUR/Day Pool
-----          ---------      ----- ------- ---------- ------- ----
CcminerKlaust  NeoScrypt  1,13 MH/s 0,00075    0,66819   5,649 zergpool-24-coin(s)
CcminerTpruvot Bitcore   19,96 MH/s 0,00035    0,01756   2,628 zergpool-1-coin(s)
CcminerTpruvot Tribus    70,85 MH/s 0,00017    0,00238   1,265 zergpool-3-coin(s)
CcminerTpruvot Skunk     37,04 MH/s 0,00014    0,00384   1,067 zergpool-3-coin(s)
CcminerKlaust  Groestl   52,37 MH/s 0,00013    0,00257   1,009 zergpool-1-coin(s)

Before adding the second GPU (750Ti) I was able to mine these:

Miner          Algorithm       Speed BTC/Day BTC/GH/Day USD/Day Pool
-----          ---------       ----- ------- ---------- ------- ----
Ccmineralexis  Sib        13.59 MH/s 0.00063    0.04625   5.458 zergpool-1-coin(s)
Ccminer-krnlx  Xevan       3.66 MH/s 0.00057    0.15690   4.980 zergpool-6-coin(s)
CcminerKlaust  NeoScrypt 934.10 KH/s 0.00048    0.51216   4.154 zergpool-23-coin(s)
CcminerTpruvot Tribus     62.56 MH/s 0.00040    0.00642   3.487 zergpool-3-coin(s)
Ccmineralexis  Blake2s     4.46 GH/s 0.00034    0.00008   2.967 zergpool-5-coin(s)
CcminerTpruvot Phi        20.21 MH/s 0.00034    0.01660   2.913 zergpool-1-coin(s)
CcminerTpruvot Bitcore    16.95 MH/s 0.00033    0.01961   2.885 zergpool-1-coin(s)
Ccmineralexis  Skein     595.42 MH/s 0.00033    0.00055   2.844 zergpool-7-coin(s)
CcminerTpruvot Skunk      32.57 MH/s 0.00029    0.00886   2.506 zergpool-2-coin(s)
Ccmineralexis  Lyra2RE2   43.15 MH/s 0.00029    0.00661   2.476 zergpool-8-coin(s)
Ccmineralexis  C11        18.37 MH/s 0.00028    0.01519   2.423 zergpool-4-coin(s)
Ccmineralexis  Hsr        13.19 MH/s 0.00026    0.01975   2.262 zergpool-1-coin(s)
Ccmineralexis  Nist5      54.24 MH/s 0.00017    0.00312   1.470 zergpool-4-coin(s)
CcminerKlaust  Groestl    46.08 MH/s 0.00013    0.00292   1.168 zergpool-1-coin(s)

**Comment by Sniffdog** [comment]
might be because of that 750.... one way to test is I have a forked nemominer in my list at git.... just need to edit the bat files... one has older ccminers and the other has newer... try them both out
