### ISSUE TITLE
issue with TPruvot Miner

### ISSUE THREAD

**Issue by btnottrue** [Sniffdog/Sniffdogminer#138]
i have an issue with TPruvot since Sniffdogminer v4.5 also appear on v4.6
there is always cuda error then crash all the time
i was DDU->Reinstall Driver doesn't help
do you guys have any clue ?
![capture99](https://user-images.githubusercontent.com/472220/36235088-2d5add6e-1221-11e8-812f-6bcdb3597686.PNG)
![capture888](https://user-images.githubusercontent.com/472220/36235089-2f000806-1221-11e8-8870-b42141835b98.PNG)

**Comment by Sniffdog** [comment]
yellow writing is warnings... red writing is bad

the pools are all aware of this but still in acceptable range

**Comment by romajc84** [comment]
What settings are you using for your 1080tis sniff?

**Comment by btnottrue** [comment]
both MSI 1080 & Zotac 1080
+120 core
+500 mem
maybe it's overclock issue
