### ISSUE TITLE
How to set intensity or restrict to certain GPU

### ISSUE THREAD

**Issue by shhyguuy** [Sniffdog/Sniffdogminer#139]
Hi, I'm wondering if there is any way to manually set intensity. Specifically, I want to set it to a lower intensity so I can still use the computer while mining.

Or alternatively, is there a way to restrict the miner to only certain GPUs? In my case, I could mine on GPU 2 & 3 and save GPU1 for normal computing, and manually turn on GPU1 when not in use.

**Comment by kodeballer** [comment]
I think thats in the .ps1 file, do a control F search for intensity once you have it open to edit

**Comment by Sniffdog** [comment]
Miners folder

Right click and edit a miners file and you will see where the intensity settings are
