### ISSUE TITLE
Stratum connection failed: Failed to connect to  port 80: Connection refused

### ISSUE THREAD

**Issue by tatsumakisen** [Sniffdog/Sniffdogminer#14]

**Comment by Sniffdog** [comment]
you should be porting to 4068...

**Comment by tatsumakisen** [comment]
How to do that ?, please

**Comment by eraser85** [comment]
I'm getting:

API open in full access mode to 0/0 on port 4068
Stratum authentication failed
... retry after 30 seconds
Stratum authentication failed
... retry after 30 seconds

and so on

**Comment by Sniffdog** [comment]
I will do a diagnostic on Sniffdog.

**Comment by imulision** [comment]
Trying to mine or benchmark an algo that is not supported by the pool return this error. I removed a bunch and now it's working for me.

**Comment by Sniffdog** [comment]
Thanks for understanding and yes that does happen.

**Comment by mullen1200** [comment]
Very happen I found this thread. The new update added x11evo which is incompatible with ahashpool if I'm not mistaken.

**Comment by Sniffdog** [comment]
yes but is compatible with zpool....

I'll tell you why....

Last year I was only running at one pool(yimp) with only a few algos.... mining was good....then someone hacked yimp pools... I was sad.... glad Sniffdog had miningpoolhub(nomp) for backup... i was happy again cause I never lost a single minute of profit for my clients

**Comment by imulision** [comment]
I have found no other way to message you, so I like to take profit from this thread to ask some questions.
In what way is sniffdogminer optimized for 1080 ti?

**Comment by Sniffdog** [comment]
Because our company runs with only 1080ti's
