### ISSUE TITLE
Issue with X11 algo in ahashpool?

### ISSUE THREAD

**Issue by romajc84** [Sniffdog/Sniffdogminer#140]
I have 15 1080tis.  They have been showing X11 as most profitable and running it 80-90% of the time on ahashpool.  However, on ahashpool I only see like 3-5 people mining it.  And I also have no coins from it.  I removed it for now but looking for reasoning and what coins it should be mining.

**Comment by jrafaelmdo** [comment]
@romajc84 Why are you mining X11 ?

X11 is not included in the .bat files as is not longer profitable to mine with gpu due to asics.

NVIDIA gpu friendly algos: blake2s,MyriadGroestl,skein,x17,neoscrypt,sib,Lyra2RE2,xevan,tribus,phi,hsr,Nist5,groestl

**Comment by Sniffdog** [comment]
Yes there are reasons as to why I leave some algo out....

**Comment by romajc84** [comment]
Yea. I didn't know. I just added all the algos for the pool. And sniffdog was showing x11 as most profitable. I wasn't purposefully mining it. I'll stick to the algos in startsniffin.bat

**Comment by Sniffdog** [comment]
yes just because it might show to be profitable.. you must figure out Global difficulty and pool difficulty.....I am extremely surprised SniffDog did not remove that algo from the list
