### ISSUE TITLE
Sniffdog howled at (zergpool) for a failed API check.

### ISSUE THREAD

**Issue by snegrom** [Sniffdog/Sniffdogminer#145]
<a><img src="https://image.ibb.co/gvVt6S/zergpool.jpg" alt="zergpool" border="0"></a>

dont think its a sniffdog problem but perhaps you know what to do or not ^^

**Comment by Sniffdog** [comment]
well i added the other api.... it's in master copy pools folder

That is all the pools side for error

**Comment by snegrom** [comment]
thanks i try

**Comment by Sniffdog** [comment]
zergool is going back to the original api link.. the other one will be shutdown in a few days

Apparently,,, zergpool got the api fixed

**Comment by sephir69** [comment]
![api](https://user-images.githubusercontent.com/2382268/36978641-04f26ee2-2053-11e8-8904-bd1baf481d93.jpg)
still getting this all time only for zergpool

**Comment by sephir69** [comment]
big pain in the butt with 240 interval and it keeps changing algos cause it can't read the pool api.  I asked in the zerg discord and changed the timeout time but that didn't help either
