### ISSUE TITLE
How long to see BTC in my wallet

### ISSUE THREAD

**Issue by Duskfall** [Sniffdog/Sniffdogminer#146]
Hello, first of all thank you for this tool!
Second, I have a question for how long shall I wait to see any BTC in my wallet.
Steps I have done

1) Git cloned the repo
2) Added my exodus BTC address to the startsniffin.bat
3) Created an account in https://www.multipool.us
4) Added a worker and changed the worker name in startsniffin.bat
5) Runned startsniffin.bat

**Comment by Sniffdog** [comment]
whenever payout is at that pool...

**Comment by Duskfall** [comment]
Thanks you for fast reply!

**Comment by Duskfall** [comment]
Since I am completely noob regarding multi mining, can you tell me if there is at least a minimum needed BTC balance so that the pools convert and send to the given BTC address?

````
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Username Duskfall -Workername worker -RigName Duskfall -Currency USD -Passwordcurrency BTC -interval 120 -Delay 1 -Wallet 1MXeLa9LHPAMVwadn8gHmTE3RMCvg6BEjb -Location US -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool,blazepool -Type nvidia,cpu -Algorithm phi,hsr,xevan,tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,blake2s,x17,lyra2z,timetravel,polytimos,ethash,yescrypt,m7m,yescryptr16

````

This is my startsniffin.bat file. Same account name and worker is used for both multipool and mining pool hub. I only see a very small balance in Mining pool hub, 0 in multipool.

**Comment by Sniffdog** [comment]
yeah I'm not sure how you even got sniffdog to multipool.......

but you are mining with asic miners....

**Comment by Duskfall** [comment]
Suprnova and many others seem pretty consistent to the numbers in USD that whattomine.com suggests. So what do you recommend to use? Only mining pool hub? I saw that it was using a lot zergpool if I remember correctly. Though I didn’t have an account there and I thought that is was fine since many of the pools use anonymous mining

**Comment by Duskfall** [comment]
So i think I understand now. You recommend SniffDog-www.zpool.ca , www.MiningPoolHub.com , www.HashRefinery.com , www.ahashpool.com , www.zergpool.com
But in your readme you suggest : Register at **Multipool** and input your -Username and -Workername to StartSniff.bat (your Workername will also be used at hashrefinery and at Zpool for identification of your rig) ***Please leave password as 'x' at Miningpoolhub

Thats why I was confused ( I think :P) So I shall only use one of them or I can create an account to all 5 of them and use the same worker and address? Can it be done without an account, just with the BTC address? Thanks again for the replies!

**Comment by Sniffdog** [comment]
ah ok so it is a mistake.. my apologies... i shall go fix that

**Comment by jrafaelmdo** [comment]
@Duskfall 

Please note that if you are mining across multiple pools it can take a while to reach the minimum payment balance.

**Comment by Duskfall** [comment]
Thanks for the clarifications guys.
