### ISSUE TITLE
zpool api failed

### ISSUE THREAD

**Issue by nlmaca** [Sniffdog/Sniffdogminer#147]
Getting several notices on 1 rig:
Sniffdog howled at (zpool) for a failed API check.

On the other rig there is no problem at all (except for the zergpool, but that has been issued before). Where can i check the state of the API call, because on 1 rig zpool is not working most of the time

on sniffdogminer 4.6

**Comment by Sniffdog** [comment]
Pools folder...

each ps1 in there has the api link

**Comment by nlmaca** [comment]
Hi, i have set the timeout a bit higher, and now it could find it several times when i restarted sniffdogminer. At the same time i did the normal api call. I can't seem to pinpoint why it gets the error, because the pool is online. Ah well, thx for the answer. i will monitor it to see if it get problems.
ticket closed
