### ISSUE TITLE
Error downloading miners with v4.6

### ISSUE THREAD

**Issue by joeyoon80** [Sniffdog/Sniffdogminer#149]
Hi. I am getting errors downloading the miners as I updated to v4.6. It only managed to download Alexis ccminer.

![sniffdog 4 6 - error](https://user-images.githubusercontent.com/32901879/36575555-7ec95b88-1886-11e8-810f-3c2d1346c437.jpg)

**Comment by Sniffdog** [comment]
i will look into this

**Comment by Sniffdog** [comment]
Thanks for catching this... It is now repaired in master and will place a new release

**Comment by joeyoon80** [comment]
No worries. Thanks for the quick response. Will await for your new compilation. Keep up the good work! :)
