### ISSUE TITLE
AMD trying to benchmark

### ISSUE THREAD

**Issue by jeremytgrant** [Sniffdog/Sniffdogminer#150]
I have been having a problems since 4.5 when when I put a clean install on my machine it is trying to benchmark Type:  AMD and I also have several Algorithm that do not have a pool.  I have been going into the miner configs and commenting out the Algorithm that do not have pools and going into all of the sgminer files and commenting out all of the Commands so they do not try to run.  I only have 2 1080 ti video cards the in my StartSniffin_Bitcoin I only have Type nvidia,cpu.  I also found the scrypt was try to benchmark today and i do not have that as an Algorithm.  What am i doing wrong.  Here is what I have in my StartSniffin_Bitcoin.bat:

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDogBitcoin.ps1 -Username nevarrie -Workername metaverse -RigName metaverse -Currency USD -Passwordcurrency BTC -interval 120 -Delay 1 -Wallet 1v
 -Location US -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool,blazepool -Type nvidia,cpu -Algorithm phi,hsr,xevan,tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,blake2s,x17,lyra2z,timetravel,polytimos,ethash,yescrypt,m7m,yescryptr16 -Donate 5

**Comment by Sniffdog** [comment]
no you just have to be patient when benchmarking all the algo's.... zpool has a couple like x11evo and polytimos... but if zpool's api is down it won't bench.... just gotta stop and try again and hope zpool's api is back online...

Yes leave AMD out if you are using nvidia....... ( -Type nvidia,cpu ) only .......amd is for those who have amd cards....

**Comment by jeremytgrant** [comment]
Should it be trying to benchmark amd if i only have -Type nvidia,cpu?

**Comment by Sniffdog** [comment]
no you shouldn't be using AMD at all....
