### ISSUE TITLE
ahashpool

### ISSUE THREAD

**Issue by Suyneej** [Sniffdog/Sniffdogminer#151]
Updated to 4.7 today. I solely use ahashpool. I notice some of the algos have been removed from the .bat file, is this because of the cryptopia issue on their website or where they removed for another reason? I believe I was using 4.5 before I updated this afternoon.

**Comment by Sniffdog** [comment]
Yes! and that was in part by Ahashpool updating their fork of SniffDog to those algo's

**Comment by Suyneej** [comment]
Thanks for the answer.
