### ISSUE TITLE
Hi there!, asking about how to overclock for each algorithm.

### ISSUE THREAD

**Issue by asupercoin** [Sniffdog/Sniffdogminer#152]
First of all i have to say i do like Sniffdog most for multipool/algo mining program. i trying to see the script files, sniffdog.ps1 or in miner folder, to add more script to run overclock batch file before mining command launch. 

batch file sample: NeoscryptOC.bat
---------------------------------------------------------
@echo off

nvidiainspector.exe -setBaseClockOffset:0,0,190 -setMemoryClockOffset:0,0,700 -setPowerTarget:0,105 -setTempTarget:0,0,85 -setFanSpeed:0,85
nvidiainspector.exe -setBaseClockOffset:1,0,190 -setMemoryClockOffset:1,0,700 -setPowerTarget:1,105 -setTempTarget:1,0,85 -setFanSpeed:1,85
nvidiainspector.exe -setBaseClockOffset:2,0,190 -setMemoryClockOffset:2,0,700 -setPowerTarget:2,105 -setTempTarget:2,0,85 -setFanSpeed:2,85
nvidiainspector.exe -setBaseClockOffset:3,0,190 -setMemoryClockOffset:3,0,700 -setPowerTarget:3,105 -setTempTarget:3,0,85 -setFanSpeed:3,85
nvidiainspector.exe -setBaseClockOffset:4,0,190 -setMemoryClockOffset:4,0,700 -setPowerTarget:4,105 -setTempTarget:4,0,85 -setFanSpeed:4,85
nvidiainspector.exe -setBaseClockOffset:5,0,190 -setMemoryClockOffset:5,0,700 -setPowerTarget:5,105 -setTempTarget:5,0,85 -setFanSpeed:5,85
---------------------------------------------------------

Can you guide me where should i add command to run batch file before the first mining round of highest profitability run? (Since the Sniffdog miner will loop the same algorithm if it is the best profitability, so i just want to run overclock batch just 1 time)

i have tried to put "start-process .\overclock\NeoscryptOC.bat" to the first line of miners script file in Miners Folder, it's work but it runs oc every time Sniffdog recalculate profit.

**Comment by Sniffdog** [comment]
if you can get Sniffdog to overclock... that would be interesting....

I'm still waiting for nvidia to catch upto the miner devs.....

Oh btw... new release has solomining with all the bells and whistles... it could be a long process of finding out the right overclock for each algo
