### ISSUE TITLE
Is the divisor for Hashrefinery correct?

### ISSUE THREAD

**Issue by GuyTechie** [Sniffdog/Sniffdogminer#153]
After mining for a couple weeks, I'm seeing that I've almost never switch to Hashrefinery.

I'm not sure if they are never the most profit, or if the divisor is wrong in Hashrefinery.ps1.

PS: I have all pools enabled: zpool, zergpool, ahashpool, MPH, blazepool, and Hashrefinery

**Comment by Sniffdog** [comment]
yah same here... only time i ever see Hashrefinery in the race is when i ran zergpool,ahashpool,hashrefinery but even then it was few and far between when you saw Hashrefinery in the lineup

Not sure what is going on with that pool... the divisors have never changed and i have tried to make contact with the operator and no reply back

**Comment by Sniffdog** [comment]
not sure but Hashrefinery has always paid us :)
