### ISSUE TITLE
Why one of miner not finishing benchmark

### ISSUE THREAD

**Issue by totalism53** [Sniffdog/Sniffdogminer#154]
The miner not finishing benchmark, so other algo can't benchmark after that.

**Comment by Suyneej** [comment]
This happened to me as well. It was the "Ccminer-krnlx" trying to benchmark Xevan algo. I just went into the miners folder, edited the krnlx file and put a # infront of Xevan so it wouldn't try and use it.

**Comment by Sniffdog** [comment]
another reason could be that one of the pools API was down during benching.... it happens

Just keep trying... and if your only benching at a certain pool then please have a look at what the pool has for algos and remove what the pool doesn't have 

Thanks
