### ISSUE TITLE
Sniffdog -ZergPool

### ISSUE THREAD

**Issue by Riones** [Sniffdog/Sniffdogminer#155]
Good evening.
I am mining with only a GTX 1080, through the file zergpool_light.bat and I am using the following code:
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&. \ SniffDog.ps1 -Username Riones -Workername Amadeu -RedName Amadeu -Currency EUR -Passwordcurrency BTC -interval 120 -Delay 1 -Wallet 37y3a2wBKcbv7ZxUzsx1rkFT8QgjRsbYAq -Location EUROPE -PoolName zergpool -Type nvidia -Algorithm hsr, c11, skein, sib, blakecoin, Nist5, MyriadGroestl, Lyra2RE2, keccak, blake2s, x17 -DONATE 0
I have tried other algorithms, but they are not accepted or give wrong connection.
Since yesterday, who only mining Lyra2re2, because she appears at 9000 € day ??? It's normal? The problem is that it mines a bit and then gives me access memory errors on the GPU ...

Am I doing something wrong?
Can you help me please.

Thank you.
Riones - from Portugal

![ccmineralexis_snifdog_zergpool](https://user-images.githubusercontent.com/36863608/36703363-3ae860b0-1b53-11e8-9f77-1ed532509df5.jpg)

**Comment by Sniffdog** [comment]
you have a corrupt file

Please goto stats folder and delete Ccmineralexis_lyra2v2 hashrate file..... it will rebench

**Comment by Riones** [comment]
Thank you very much, for helping me.
I delet and install again everything and it works.
Now I'm minning the algos: Lyra2RE2,hsr,c11,skein,sib,Nist5,MyriadGroestl,keccak,blake2s,x17 on my GTX1080. (only works they)

Now I have this working:
![ccmineralexis_snifdog_zergpool_](https://user-images.githubusercontent.com/36863608/36760827-3fccef08-1c14-11e8-89b8-dd787cdf6eb6.jpg)


I see other peolpe with more Minners/pools, and the system, just pull in first the best algo at the moment.
Can you show for me, How I put more minners/pools doing the Job? (and not only the ccminerAlexis/zergpool.

Thank you very much, and sorry my bad English.
Best regards.

**Comment by Sniffdog** [comment]
Well for one.... that looks like an older sniffdog.... so I'm not sure where you downloaded from

If you download the latest SniffDogminer you will have all the pools

**Comment by Riones** [comment]
So, that's why I have today no pools...no pools...no pools.
Where I have to download? To put many miners and pools work.
Is not here? zergpool.com

Thank you.

**Comment by Sniffdog** [comment]
Sorry for late reply

Always good to have a backup pool

And from what I heard zergpool is getting better now

Latest SniffDog is here https://github.com/Sniffdog/Sniffdogminer/releases
