### ISSUE TITLE
What is correct process of the miner updating?

### ISSUE THREAD

**Issue by sertony** [Sniffdog/Sniffdogminer#157]
Recently I've faced an issue that every time when I download a new release it takes a lot of time to benchmark all the algorithms again.
Can I somehow keep all the benchmarked results to continue mining immediately when a new version is released. It'd be great to make a note of an updating process in README file.

Thank you in advanced.

**Comment by santaniitr** [comment]
If you copy the files in Stats folder then i think you don't need to benchmark again.

**Comment by sertony** [comment]
@santaniitr thank you, I'll try.
