### ISSUE TITLE
Nvidia btc/day stats

### ISSUE THREAD

**Issue by ayalu** [Sniffdog/Sniffdogminer#158]
Hi,

Congrats for this project :)  I'd like to know if you have profit stats for 1080 TI (last 30 days btc/day average) and how Sniffdog profit compares to Nicehash ?

thank you !

**Comment by Sniffdog** [comment]
Nope gotta keep SniffDog a simple, light end, software for big rig applications....

Do what we do..... take your balance at the end of the month that is in your wallet and divide by the number of days in the month OR spreedsheet monthly like we do to show how our company is doing for the year

**Comment by ayalu** [comment]
I understand, I just wanted to get your (or others) stats :) 
I also wanted to know if anyone was able to beat Nicehash miner profit stats with sniffdog because I can't .....  Always lower  ..

**Comment by Sniffdog** [comment]
well you better stick with Nicehash if your profits are higher there...
