### ISSUE TITLE
Variance checker

### ISSUE THREAD

**Issue by alexg1980** [Sniffdog/Sniffdogminer#159]
Hello,

Will you be so kind to explain this variance checker:
SniffDog sniffs 23% and upto 47% more profit than the fastest (listed) miner:

Miner                  USD
-----                  ---
Sniffdog.. sniffs out! 19.92036 ±25% (15.96988-24.84808)
{Ccminer-krnlx-, JayDDeecpuavx2-} 13.98225 ±0% (13.98225-13.98225)

with more details? Does this mean, that the script compares the current combo of miner/algo/pool with everything available (even not the listed in the bat file), and it warns, that there is a more profitable combo, or is it something else? And what about the last line?
  I found very scarce info about this checker, and it bothers me constantly.

Kind regards,
Alex

**Comment by Sniffdog** [comment]
Yes......... cause now you will be one of the few that knows...... Price and Luck fluctuates wildly on any day

So how could you do a 24 hour actual?

**Comment by alexg1980** [comment]
OK, help me understand the meaning of each part of the checker please, because now it's pretty unclear to me. I don't ask how to use it and be the guru of trading/mining, but just to clarify it.

**Comment by Sniffdog** [comment]
of course 

it starts out at +/-50% and as the miners keep working over time the variance adjusts (Cool) Daily

now bottom shows miners at +/- 0% so shows no variance (Cool) Running live

so all miners running that day gets factored in (Cool)

And if you keep on and not erase your profit.... the variance checker will keep recording(daily)

I could use weekly.... but then nobody ever wants to do weekly variance checks

**Comment by asupercoin** [comment]
You mean we need to erase the profit? By run "ResetSniffProfit"?

**Comment by Sniffdog** [comment]
I'm not saying you need to do nothing....... Guys... its a variance indicator,,, nothing more

**Comment by sephir69** [comment]
it's very scary lol

**Comment by Sniffdog** [comment]
and probably why none of the other multiminers wants to show you.... but you should need to know this as a professional mining that price variance swings are here to stay with us
