### ISSUE TITLE
BTC null

### ISSUE THREAD

**Issue by frederikvanduuren** [Sniffdog/Sniffdogminer#16]
sometimes i get no value for btc rate
as such that the latest algo keeps on mining

is there an extra check possible to code so it could use previous btc rate or restart the api scan?

thanx

**Comment by Sniffdog** [comment]
Not at this time. All I do is place my computer on reboot every 24 hours

**Comment by frederikvanduuren** [comment]
could be an easy code? no?
yesterday, it mined for 4 hours the same algo :(
ideas?

**Comment by Sniffdog** [comment]
No sorry I do not own the universal API. I will check into others

**Comment by luk3r88** [comment]
should be fixed with change to coinbase at 7ad0323af08a25134a8a5b0dc399f45d0acc63f9

**Comment by Sniffdog** [comment]
yes I have been at my desk watching Sniffdog and coinbase has been working good
