### ISSUE TITLE
Missing StartSniff.bat

### ISSUE THREAD

**Issue by lovingkrypto** [Sniffdog/Sniffdogminer#162]
Hi guys,

if I follow the descriped steps, i had to modify the StartSniff.bar file, but there is only a StartSniffin.bat. Is that the correct file??

Beside that, i red in the extracted readme file, that i have to exempt the sniffdocg folder before running, but i cant see any folder like that. Any ideas?

Thanks a lot!

**Comment by Sniffdog** [comment]
1)StartSniffin.bat file yes edit

2) Only if your antivirus is not letting you use SniffDog
