### ISSUE TITLE
CPUminer avx2 stopped working.

### ISSUE THREAD

**Issue by ijsilva0123** [Sniffdog/Sniffdogminer#163]
Hi, i have this direct warning on my screen. My processor is a Celeron, and I did not want to mine with it, only with my GPU. Is there any way to turn off this CPUminer?

**Comment by Jude-Masson** [comment]
-Type nvidia,cpu - delete cpu file StartSniffin*.bat

**Comment by Sniffdog** [comment]
and remove yescrypt,M7M,yescryptr16

all cpumine coins

**Comment by ijsilva0123** [comment]
Ok, its working. thanks.
