### ISSUE TITLE
24 hour option gone

### ISSUE THREAD

**Issue by kodeballer** [Sniffdog/Sniffdogminer#165]
I was just starting to appreciate this , and utilizing it, then poof gone from current releases.

Could you also put version numbers on your releases as well, thanks i donated for 24 hours the other day with three 1080ti's and a 1070 rig!

**Comment by Sniffdog** [comment]
not sure what you mean @kodeballer I have always placed a tag on all my versions

**Comment by kodeballer** [comment]
The .bat that takes 24 hour averages and mines the algorithm with the highest yield over 24 hours.
So in previous releases of sniffdog there was multiple .bat for same pool, a 24 hour one and a regular.bat, I no longer see the 24 hour one on current releases.

I had your wallet address entered, and therefore ran the rig for 24 hours.

**Comment by kodeballer** [comment]
just realized its nemo's that has this feature, would be nice to see it with sniffdog. Closing this out.
