### ISSUE TITLE
Possible to manual edit stat?

### ISSUE THREAD

**Issue by asupercoin** [Sniffdog/Sniffdogminer#167]
Since X17 takes around 10-15 mins to get the highest speed and i don't want to benchmark, if it is possible to manual edit stat file.

x17 benchmark is 62.67 MH/s and stat file is the following

{
    "Live":  0.0000000000249381,
    "Minute":  0.0000000000249381,
    "Minute_Fluctuation":  0.19879134860050884,
    "Minute_5":  0.0000000000249381,
    "Minute_5_Fluctuation":  0.19879134860050884,
    "Minute_10":  0.0000000000249381,
    "Minute_10_Fluctuation":  0.19879134860050884,
    "Hour":  0.0000000000239585444275735,
    "Hour_Fluctuation":  0.28974774260103303,
    "Day":  0.0000000000230744607913254,
    "Day_Fluctuation":  0.3266754962309576,
    "Week":  0.0000000000230462306227486,
    "Week_Fluctuation":  0.45754549413252332,
    "Updated":  "\/Date(1520187368272)\/"
}

------------------------------------------------

But for the actual speed is around 71 MH/s. Can i edit stat file myself instead of re-benchmark?

Thank you.

**Comment by Sniffdog** [comment]
yes of course

then you can -StatsInterval 10000 so it won't change stat...
