### ISSUE TITLE
Split-Path error

### ISSUE THREAD

**Issue by tokpanov** [Sniffdog/Sniffdogminer#168]
When running sniffdog I get the following error:

> PS>TerminatingError(Split-Path): "Cannot bind argument to parameter 'Path' because it is null."
> Split-Path : Cannot bind argument to parameter 'Path' because it is null.
> At D:\Sniffdogminer-master\SniffDogBitcoin.ps1:135 char:28
> +             if((Split-Path $Miner.URI -Leaf) -eq (Split-Path $Miner.P ...
> +                            ~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : 
> ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
> Split-Path : Cannot bind argument to parameter 'Path' because it is null.
> At D:\Sniffdogminer-master\SniffDogBitcoin.ps1:135 char:28
> +             if((Split-Path $Miner.URI -Leaf) -eq (Split-Path $Miner.P ...
> +                            ~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand

Can it be ignored?

**Comment by Sniffdog** [comment]
any more info?... is your miner being removed possibly by your antivirus?

**Comment by Sniffdog** [comment]
ok I'll download latest copy

**Comment by tokpanov** [comment]
No, I excluded sniffdog folder from my antivirus. Mining actually run normally, I can see my balance accumulating in pools.

What additional info do you need?

**Comment by Sniffdog** [comment]
I'm actually not to sure now what I need..... if your up and running all good!
