### ISSUE TITLE
Sniffdog howled at (zergpool) for a failed API check

### ISSUE THREAD

**Issue by sephir69** [Sniffdog/Sniffdogminer#169]
![api](https://user-images.githubusercontent.com/2382268/36986626-4bc8b460-2068-11e8-8689-00d35de50531.jpg)

getting this all the time for zergpool, other pools are fine

**Comment by Sniffdog** [comment]
SniffDog can't fix pool's api.... just keep restarting sniffdog till you receive the api call if you wanna mine at zergpool
