### ISSUE TITLE
try to start but with errors

### ISSUE THREAD

**Issue by hhoertner** [Sniffdog/Sniffdogminer#170]
when I try to start the following error massage appear...
ConvertFrom-Jason: The length should not be less than zero (0)
Parametername: length....

any ideas?
THX

**Comment by Sniffdog** [comment]
yes if it's sniffdoglitecoin it has the old cryptonator api

no worries... coinbase is also in there to just to make sure

did you miner run?

Were you able to algo switch?

**Comment by hhoertner** [comment]
no the miner is not running..
is only the DOS/Powershell Windows open with tonns of red massege Scrolling up... ;-)

**Comment by Sniffdog** [comment]
crazy that i don't have more users mentioning this

is your powershell up to date?

**Comment by hhoertner** [comment]
hm creazy I downloaded the whole package again now it works!
but I have some errors when the program wants to download miners...
can I download the miner manualy and put the miner in a Spezial Folder?
