### ISSUE TITLE
ccminer TruvpotEnemy problems

### ISSUE THREAD

**Issue by russellt83** [Sniffdog/Sniffdogminer#171]
This miner requires special underclocking to make stable. Not really compatible with the other miners which use a reasonable overclock.

**Comment by Sniffdog** [comment]
ok 2.2.5 is in sniffdog you can turn off enemy and use that?

**Comment by jrafaelmdo** [comment]
@russellt83 @Sniffdog 

Please stay away from Enemy miner, the creator never released the true source code, and has been pointed that it might contain malware or dev fee.

http://cryptomining-blog.com/9507-ccminer-enemy-1-03-fork-for-raven-rvn-mining-now-available
https://bitcointalk.org/index.php?topic=2752467.msg31603074#msg31603074

Conveniently the "dev" has deleted their github page
https://github.com/Enemy-Mine

**Comment by Sniffdog** [comment]
pretty hard not to stay away from it now.....

master copy is edited.....

You all do with what you want to copies that you have of Enemy.....

I hope there was a dev fee.... the dev deserved it

**Comment by Nickduino** [comment]
If you want to disable a miner, you just have to put a # in front of all its algos in the /miners/ folder, right?

**Comment by Sniffdog** [comment]
yes
