### ISSUE TITLE
Phi Algo crashes

### ISSUE THREAD

**Issue by frederikvanduuren** [Sniffdog/Sniffdogminer#18]
HI,

it seems to crash/loop-forever on the PHI algo...

this is my second crash just on that algo

possible?
i reboot my computer every day
i do rescan every 60 seconds & wait 2 seconds...

any ideas?

fred

**Comment by Sniffdog** [comment]
Not sure as to why yet.... You are using Tpruvot ccminer for PHI. One of the most stable out there. Maybe its a pool issue?

**Comment by frederikvanduuren** [comment]
i dont think its ccminer Tpruvot related, its just bad luck that the batch stops looping for some strange reason...
will try to send a log file next time ;)
fred

**Comment by Sniffdog** [comment]
yeah I have been running both 2.5 versions of sniff and nothing is wrong with phi algo......

**Comment by frederikvanduuren** [comment]
ok cool

no issues for the last few days reported ;)

fred
