### ISSUE TITLE
GPU crashed 4.8.3

### ISSUE THREAD

**Issue by kingyem** [Sniffdog/Sniffdogminer#182]
Hello,

I am not sure of the cause, but since using 4.8.3 my 2nd GPU crashes everytime. It usually happens sometime after starting sniffdog.

**Comment by kingyem** [comment]
Update- i tried a different multialgo miner, and the above crash doesn't happen. not sure what to attach because i don't notice anything wrong in the log file

2 GPU starts mining, then after awhile GPU 2 crashes while GPU 1 still mines

**Comment by knottyuminus** [comment]
Usually when it crashes you can still see ccminer.exe windows, just look up which algo it is and change it's intensity to be lower, or you can just remove it from .bat file.

**Comment by kingyem** [comment]
yeah i think that makes sense, thanx
