### ISSUE TITLE
Optimized CCMiner (CUDA miner) fork for x16r

### ISSUE THREAD

**Issue by nemosminer** [Sniffdog/Sniffdogminer#193]
https://github.com/nemosminer/Ccminernevermore/releases

Optimized CCMiner (CUDA miner) fork for x16r

Forked from https://github.com/tpruvot/ccminer
Alexis78 x16r support added by "brian112358" : https://github.com/brian112358/nevermore-miner
disabled fee and recompiled: https://github.com/nemosminer/Ccminernevermore

Initial release. Windows 32-bit

11-hour side-by-side comparison on 1080 Ti show 20% increased hashrate over ccminer-2.2.5

compiled with vs2013 cuda 9 32bit

Best Regards
Nemo

**Comment by Sniffdog** [comment]
Get off my chat nemo
