### ISSUE TITLE
Nemo.... stay off this thread and quit promoting.....

### ISSUE THREAD

**Issue by Sniffdog** [Sniffdog/Sniffdogminer#194]
the new x16r miner is already been pull requested and accepted in master copy...

Now SniffDog has three x16r algo miners

**Comment by nemosminer** [comment]
promoting.... if you say so "Sniffdog"

**Comment by nemosminer** [comment]
you don't need three miners for one ALGO just the fastest one... https://github.com/nemosminer/ccminernevermore/releases

**Comment by nemosminer** [comment]
you could just say Thankyou...   https://github.com/Quake4/MindMiner/issues/28

**Comment by nemosminer** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1507

**Comment by nemosminer** [comment]
Note: compiled and tested x64 release performed better than 32bit
seems cuda 9 favors x64 over 32bit

**Comment by nemosminer** [comment]
https://bitcointalk.org/index.php?topic=826901.msg33270611#msg33270611

**Comment by nemosminer** [comment]
fastest x16r ccminer Availible :https://github.com/nemosminer/ccminernevermore/releases

**Comment by nemosminer** [comment]
https://bitcointalk.org/index.php?topic=826901.new#new

**Comment by Sniffdog** [comment]
show your nemominer link..... one more time.....

https://github.com/brian112358/nevermore-miner/releases will be the default  x16r with the 1% dev fee

**Comment by nemosminer** [comment]
ccminer fork for x16r & x16s Algorithms

v0.4 

https://github.com/nemosminer/ccminerx16r-x16s/releases

Best Regards
Nemo

**Comment by Sniffdog** [comment]
you have been reported....
