### ISSUE TITLE
Potential Issue with new KlausT and NeoScrypt

### ISSUE THREAD

**Issue by h-parks** [Sniffdog/Sniffdogminer#20]
2.8, using KlausT's latest version, seems to have a ton of rejected Neoscrypt shares from ahashpool than previous versions. Is anyone else experiencing this?

**Comment by Sniffdog** [comment]
Never checked for that. I'll keep an eye on it! Thank you

**Comment by Sniffdog** [comment]
Been checking all day and using older version of Klaust... I get a lot more of "Does not validate on cpu" with older versions..... Keeping Klaust at latest version. Thank you!
