### ISSUE TITLE
Error ConvertFrom-Json

### ISSUE THREAD

**Issue by Frunzl** [Sniffdog/Sniffdogminer#204]
I am getting this on start and after every refresh interval.
Must admit, I also tinkered a bit, such as replacing estimate_current with actual_last24h in pool.ps1
Would be grateful for some help!

ConvertFrom-Json : Ungültiger JSON-Primitiv: ..
In C:\Users\...\Sniffdogisgreat\Include.ps1:127 Zeichen:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by Sniffdog** [comment]
removed two x16r miners from the list and updated enemy 1.04a and 1.05a zip packages in bin folders

Doing a test now.... had to re-add x17 to alexis and no red writing is coming up
