### ISSUE TITLE
Qubit / Quark USD$1500 per day on 1x nv1070Ti ?

### ISSUE THREAD

**Issue by Rimplestilhskin** [Sniffdog/Sniffdogminer#206]
Good day, I noticed several multi mining software shows Qubit / Quark at USD$1000+ for 1 single NV1070ti, stats on pools shows it is a fraction of this closer to normal USD$1-2 per day.

Mostly shows up on zpool, nicehash, ahashpool in SniffDogMiner / other similar mining software.

How can I fix this ?

**Comment by Sniffdog** [comment]
I'll look into it.... you need divisors on each pool for qubit and quark

not sure why you are mining asic.....

**Comment by Rimplestilhskin** [comment]
Thank you removed quark & cubit, thank you for other recent updates, highly appreciated. will mine 1 days a week as donation.
