### ISSUE TITLE
cant start the program

### ISSUE THREAD

**Issue by KillSwitch00418** [Sniffdog/Sniffdogminer#21]
I have registered at multipool, entered in my username and worker name. I entered in my BTC address as well into the batch file. However everytime i try to run startsniffin this red line shows up in the prompt.
& : The term '.\SniffDog.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
What am I doing wrong? I have Windows 10 Pro, with a 6700k and 1080Ti, 15Gof ram. I have powershell, although I'm not sure it's 5.0. I have tried to install it from windows download center, but every single option tells me once i open that the update isn't applicable to my computer.

**Comment by Sniffdog** [comment]
You have to give permission... A blue screen will pop up asking you to run the startsniff.bat 

You may have to restart all over again

**Comment by KillSwitch00418** [comment]
What do I have to give permission to? The installer for power shell installer? The sniff dog bat file? Every time I run that I right click to open as administrator or else it won’t start. I have reinstalled 3 times with the same result, what am I missing? Is there like a thing I have to do to give permission?

**Comment by Sniffdog** [comment]
yes the startsniff.bat has a blue screen which asks you what to do with the program.... you need to click on more info and then click on run anyways....

Then once you begin to run the powershell program another permission screen ask you to continue... you want to continue....

Then there is a third permission for the Tpruvot ccminer... you need to allow that....

If those do not pop up then maybe exempt your antivirus program from the folder(something is blocking the program from running)

Hope this helps

**Comment by Sniffdog** [comment]
CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145 | CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145 | CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145
-- | -- | --
CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145 | CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145
CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by KillSwitch00418** [comment]
i appreciate your help but i cant get this to work. first of all, there is no startsniff.bat file, its called startsniffin, which im going to assume is what youre referring to. second, when i run the bat file, i get a cmd prompt that pops up saying the same thing every time. my antivirus (windows defender) isnt doing anything i have disabled it just in case. at this point i have spent a few frustrating hours on this thing to no avail. is there nothing i can do? im finally about to give up

**Comment by Sniffdog** [comment]
Yes startsniffin...sorry my bad 

If you have Windows 7, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395 | If you have Windows 7, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395 | If you have Windows 7, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395
-- | -- | --
If you have Windows 7, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395 | If you have Windows 7, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395
If you have Windows 7, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395

**Comment by Sniffdog** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=53587 | https://www.microsoft.com/en-us/download/details.aspx?id=53587 | https://www.microsoft.com/en-us/download/details.aspx?id=53587 | https://www.microsoft.com/en-us/download/details.aspx?id=53587
-- | -- | -- | --
https://www.microsoft.com/en-us/download/details.aspx?id=53587 | https://www.microsoft.com/en-us/download/details.aspx?id=53587 | https://www.microsoft.com/en-us/download/details.aspx?id=53587
https://www.microsoft.com/en-us/download/details.aspx?id=53587 | https://www.microsoft.com/en-us/download/details.aspx?id=53587
https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by KillSwitch00418** [comment]
i have also previous tried to install those things, but everytime, the installer would say that the update isnt applicable to my computer. i also dont understand the difference between win8.1 vs win7 vs w2k12 since im using windows 10. ive never had an issue with installing anything before, i just dont understand what the problem is. i have tried every installer for every single link given, nothing

**Comment by Sniffdog** [comment]
I'm not sure... I have bought Win 10 64bit home and started Sniffdog right away to my rigs. Sniff runs on cuda 9 and up to date nvidia. I wish I could help you any further.....

**Comment by KillSwitch00418** [comment]
thank you anyways, appreciate the help

**Comment by dictuss** [comment]
@KillSwitch00418 

From what you wrote in the first reply you should be using x64 version of Windows 10 Pro. 

You can check Powershell version you have installed with following command in Powershell: "$PSVersionTable.PSVersion"

Also to be able to run PowerShell scripts make sure you run this command as well in PowerShell on your computer: "set-executionpolicy unrestricted -force" (make sure you start Powershell as an Admin with elevated permissions)

To be able to see the extensions of the files, you can start an Explorer window then navigate to menu: View>Options>View and uncheck the option: "Hide extensions for known file types"

I hope it helps.
