### ISSUE TITLE
zergpool alternate ports

### ISSUE THREAD

**Issue by sephir69** [Sniffdog/Sniffdogminer#210]
$zergpool_Port = If ($zergpool_Request.$_.name -eq "x17"){ 3738 }else{ $zergpool_Request.$_.port }

im using this in the zergpool.ps1 file but how do I add alternate ports for more than 1 algo?

Even better is there a way you can make a setting to always go to the zergpool alternate port because there is no load balancing so the default always crashes when full?

**Comment by Frunzl** [comment]
$zergpool_Port = if($zergpool_Request.$_.name -eq "X17"){ 3738 }
					 elseif($zergpool_Request.$_.name -eq "x16r"){ 3637 }		
					 else {$zergpool_Request.$_.port}

**Comment by sephir69** [comment]
pinpin starting to load balance no need now
