### ISSUE TITLE
Showing no pools!

### ISSUE THREAD

**Issue by abinsraj** [Sniffdog/Sniffdogminer#212]
Hi, 
Yesterday onward i'm facing no pool issue in sniffdog miner. Currently I'm mining in ahashpool. Please help me out...
![no pools](https://user-images.githubusercontent.com/34397058/39171133-84d58f42-47bb-11e8-8434-c753ea185725.PNG)

**Comment by Sniffdog** [comment]
ahashpool was down 17 hours ago but it appears to be running today

**Comment by abinsraj** [comment]
@Sniffdog thanks man.
Please close this thread.
