### ISSUE TITLE
Cannot benchmark/mine x11 zergpool

### ISSUE THREAD

**Issue by DDCS222** [Sniffdog/Sniffdogminer#213]
Sniffdog doesn’t benchmark or mine x11... when benchmark starts it goes on for some time, then stops, algorithm dissapears from the list of algos, and thats with all miners...

**Comment by Sniffdog** [comment]
probably because zergpool has their stratum diff so high that Sniffdog thought it wasn't a money maker...so deleted it....

that is a asic algo... yes gpu can mine but not very good profit
