### ISSUE TITLE
filter algo by pool

### ISSUE THREAD

**Issue by sephir69** [Sniffdog/Sniffdogminer#215]
Is it possible to do so?  I like to mine from zpool and zerg but find sometimes i'd like to pick a certain algo to run on zerg and another on zpool.

**Comment by Sniffdog** [comment]
ah ok well ill tell you a little trick

take hsr file.....Alexis

![screenshot 98 _li](https://user-images.githubusercontent.com/30452757/39403966-b055befc-4b45-11e8-9fc2-4af6b2ce6003.jpg)

you can edit the spot in blue to match the mining directory for zpool..... and save it as a different file....

then whenever Sniffdog pickups HSR... it will mine to zpool...
