### ISSUE TITLE
Sniff rate a lot higher than zergpool reported

### ISSUE THREAD

**Issue by psynauty** [Sniffdog/Sniffdogminer#219]
On Zergpool, I've increasing interval to 600 and dropped spikey algos (only using phi,skein,xevan,c11,x16r/s,lyra2rev2,neoscrypt,hsr,Tribus but the reported sniffdog rate shows a lot higher than what zergpool reports. 
![image](https://user-images.githubusercontent.com/37837131/39746759-3ea68498-52a3-11e8-82e5-34af7b9b1bd4.png)
Sniff reports 0.00422 - 0.00667 BTC but zergpool stats I'm barely getting 2.4 - 3mBTC from zergpool /day so where is the delta coming from? 
Running 9x 1080 Tis undervolted and OCed.
Running latest enemy 1.08
Thank you.

**Comment by Sniffdog** [comment]
yes thats a swing indicator... doesn't predict price ....only swings

**Comment by Sniffdog** [comment]
it shows that no matter how much you try to predict anything... you must accomodate for swings which is almost impossible

**Comment by Sniffdog** [comment]
because its a battle of the API...

This has nothing to do with SniffDog....

**Comment by psynauty** [comment]
battle of the API? I'm clueless sorry :(

**Comment by sephir69** [comment]
api is what gives estimate of profit(every pool is different), sniff number is showing swings.  The algo's you said you left are also very spikey... what did you actually remove?

**Comment by psynauty** [comment]
I have these (phi,skein,xevan,c11,x16r/s,lyra2rev2,neoscrypt,hsr,Tribus) and removed timetravel and hmq1725 as I've been told that they are even more spikey.
Shouldn't the profit switching deal with the spikey behaviour? I was using the default interval of 120 and went to 600 but no difference. Do you have a recommendation for algos and interval combo I could try out?
Thanks again

**Comment by sephir69** [comment]
i was using 600 and only x17,x16r,x16s,lyra2v2,hsr on zerg(probably good to throw in lyra2z as well but I missed the boat on that one),  I'm trying out blazepool atm with even more algo's and a lower 300 interval, seems to be making more on blazepool running for 24 hours.  Still switching pretty often but since the pool is smaller you miss less blocks from switching all the time, only logic I can think of anyway.

**Comment by psynauty** [comment]
I'm doing the same now. Switched to blazepool to compare with 300 interval and more algos. Will see. If all fails, I'll switch to nicehash. Less variance, and easier control of the setup but less algos
