### ISSUE TITLE
[feature request] Please make this script run without admin permissions and compatible with kaspersky

### ISSUE THREAD

**Issue by dc232** [Sniffdog/Sniffdogminer#22]
Hi the following error are observed when running the sniffdog PowerShell scripts with Kaspersky
**********************
Transcript started, output file is .\Logs\2017-12-12_00-13-21.txt
At F:\Sniffdogminer-master\Sniffdogminer-master\Miners\Ccminerpalgin.ps1:1 char:1
+ . .\Include.ps1
+ ~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
At F:\Sniffdogminer-master\Sniffdogminer-master\Miners\Ccminerpalgin.ps1:1 char:1
+ . .\Include.ps1
+ ~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

At F:\Sniffdogminer-master\Sniffdogminer-master\Miners\EWBF.ps1:1 char:1
+ . .\Include.ps1
+ ~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
At F:\Sniffdogminer-master\Sniffdogminer-master\Miners\EWBF.ps1:1 char:1
+ . .\Include.ps1
+ ~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

Rename-Item : Access to the path 'F:\Sniffdogminer-master\Sniffdogminer-master\Bin\ccminer-polytimos_v2' is denied.
At F:\Sniffdogminer-master\Sniffdogminer-master\Include.ps1:534 char:5
+     Rename-Item "$(Split-Path $Path)\$FolderName_Old" "$FolderName_Ne ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (F:\Sniffdogmine...er-polytimos_v2:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand
Rename-Item : Access to the path 'F:\Sniffdogminer-master\Sniffdogminer-master\Bin\ccminer-polytimos_v2' is denied.
At F:\Sniffdogminer-master\Sniffdogminer-master\Include.ps1:534 char:5
+     Rename-Item "$(Split-Path $Path)\$FolderName_Old" "$FolderName_Ne ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (F:\Sniffdogmine...er-polytimos_v2:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand

This command cannot be run due to the error: Access is denied.
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
    + PSComputerName        : localhost
This command cannot be run due to the error: Access is denied.
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
    + PSComputerName        : localhost

If Kaspersky is disabled the script  runs but I get an error 
[2017-12-12 00:24:34] Stratum connection failed: Failed to connect to  port 80: Connection refused
[2017-12-12 00:24:34] ...retry after 30 seconds

after around  5 minutes the sniffdog script seems to work in which different windows are seen for example zcash etc. are these suppose to be static?

Also, I received a firewall window for ccminer-x64.exe is this normal operation for this script?

Is there a way to bypass benchmarking and go straight to mining?

**Comment by Sniffdog** [comment]
Nope... the benching needs to happen and yes you need to exempt Sniffdog because zminer will be removed from your antivirus program for equihash mining...

**Comment by dictuss** [comment]
Little tutorial on how to add exclusions in Kaspersky: 

[https://youtu.be/RsLkhRX-4HI](url)

I hope it helps.
