### ISSUE TITLE
Can't see hmq1725 on Blazepool 

### ISSUE THREAD

**Issue by psynauty** [Sniffdog/Sniffdogminer#220]
Algos enabled in start file and supported by Blazepool but don't show when sniffdog is running.

**Comment by Sniffdog** [comment]
did you try only blazepool for algos?

**Comment by sephir69** [comment]
they don't have equi on blaze

**Comment by psynauty** [comment]
Ah true that. Was more interested in the hmq one which is on blaze. Not sure why I saw equi was on it.

**Comment by Sniffdog** [comment]
did you try just Blazepool in your start batch file?

**Comment by psynauty** [comment]
Yes

**Comment by psynauty** [comment]
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDogBitcoin.ps1 -StatsInterval 1 -Username psynauty -Workername RIGSniffDog -RigName RIGSniffDog -Currency BTC -Passwordcurrency BTC -interval 300 -Delay 1 -Wallet 39LBawvvL4BVSi9bKyEtAFDzh5hh3kAf2b -Location US -PoolName blazepool -Type nvidia -Algorithm c11,phi,hsr,Lyra2RE2,x17,x16r,x16s,tribus,hmq1725,skein,neoscrypt,xevan -Donate 0

**Comment by Sniffdog** [comment]
yup noticed... they must have fixed hmq1725 since last update

I will remove the divisor from blazepool.ps1 in pools folder

**Comment by psynauty** [comment]
I removed the divisor line from blazepool.ps1 and hmq1725 kicked in. Thanks.
