### ISSUE TITLE
Edit EWBF.ps1

### ISSUE THREAD

**Issue by Rimplestilhskin** [Sniffdog/Sniffdogminer#226]
Edit \\ to  \
$Path = ".\Bin\NVIDIA-EWBF\\miner.exe" -> $Path = ".\Bin\NVIDIA-EWBF\miner.exe"

**Comment by Sniffdog** [comment]
please elaborate

**Comment by Rimplestilhskin** [comment]
Sorry post should be this with \\ and edit to only single \ but somehow github refuses to post this double \\ even when editing the post above

$Path = ".\Bin\NVIDIA-EWBF\\miner.exe"
$Uri = "https://github.com/Sniffdog/ewbf-miner-btg-edition/releases/download/v0.3.4b/ewbf-miner-btg.zip"

**Comment by Rimplestilhskin** [comment]
Okay again. broken github, see double \  \ in in file.
