### ISSUE TITLE
Miner app updated ExcavatorNvidianeo.ps1 - 11 May 2018

### ISSUE THREAD

**Issue by Rimplestilhskin** [Sniffdog/Sniffdogminer#227]
https://github.com/nicehash/excavator/releases
excavator_v1.5.3a_NVIDIA_Win64.zip

https://github.com/nicehash/excavator/releases/download/v1.5.3a/excavator_v1.5.3a_NVIDIA_Win64.zip

edit old:
$Threads = 1

$Path = ".\Bin\Excavator\excavator.exe"
$Uri = "https://github.com/nicehash/excavator/releases/download/v1.4.4a/excavator_v1.4.4a_NVIDIA_Win64.zip"

New:
$Threads = 1

$Path = ".\Bin\Excavator\excavator.exe"
$Uri = "https://github.com/nicehash/excavator/releases/download/v1.5.3a/excavator_v1.5.3a_NVIDIA_Win64.zip"

**Comment by Rimplestilhskin** [comment]
Same for nv1080+ cards
ExcavatorNvidianeo1080andlower.ps1

**Comment by sephir69** [comment]
from what i can see in the readme it only works on nicehash stratum servers

**Comment by Rimplestilhskin** [comment]
@sephir69 True, nicehash is not profitable on only 1x gpu.
