### ISSUE TITLE
New Miner - SgminerNeoscrypt.ps1 - 0.9.4

### ISSUE THREAD

**Issue by Rimplestilhskin** [Sniffdog/Sniffdogminer#230]
Edit:
. .\Include.ps1

$Path = ".\Bin\NeoScrypt-AMD\nsgminer.exe"
$Uri = "https://github.com/ghostlander/nsgminer/releases/download/nsgminer-v0.9.4/nsgminer-win64-0.9.4.zip"

**Comment by Sniffdog** [comment]
can you throw in optimizations for sgminer please

**Comment by Rimplestilhskin** [comment]
I found this, looks like it is AMD specific, hope it can help. Cudos to the original content creators of this below.

$Commands = [PSCustomObject]@{
    #"bitcore" = "" #Bitcore
    #"blake2s" = "" #Blake2s
    "blake" = "" #Blakecoin
    "vanilla" = " --intensity d" #BlakeVanilla
    #"c11" = "" #C11
    #"cryptonight" = " --gpu-threads 1 --worksize 8 --rawintensity 896" #CryptoNight
    "decred" = "" #Decred
    #"equihash" = " --gpu-threads 2 --worksize 256" #Equihash
    #"ethash" = " --gpu-threads 1 --worksize 192 --xintensity 1024" #Ethash
    "groestlcoin" = " --gpu-threads 2 --worksize 128 --intensity d" #Groestl
    #"hmq1725" = "" #HMQ1725
    #"jha" = "" #JHA
    "maxcoin" = "" #Keccak
    "lbry" = "" #Lbry
    "lyra2rev2" = " --gpu-threads 2 --worksize 128 --intensity d" #Lyra2RE2
    #"lyra2z" = " --worksize 32 --intensity 18" #Lyra2z
    "myriadcoin-groestl" = " --gpu-threads 2 --worksize 64 --intensity d" #MyriadGroestl
    "neoscrypt" = " --gpu-threads 1 --worksize 64 --intensity 15" #NeoScrypt
    #"nist5" = "" #Nist5
    "pascal" = "" #Pascal
    "sibcoin-mod" = "" #Sib
    "skeincoin" = " --gpu-threads 2 --worksize 256 --intensity d" #Skein
    #"skunk" = "" #Skunk
    #"timetravel" = "" #Timetravel
    #"tribus" = "" #Tribus
    #"veltor" = "" #Veltor
    #"x11evo" = "" #X11evo
    #"x17" = "" #X17
    "yescrypt" = " --worksize 4 --rawintensity 256" #Yescrypt
    #"xevan-mod" = " --intensity 15" #Xevan
}

Alternative is this: 

$Commands = [PSCustomObject]@{
    "neoscrypt" = " --gpu-threads 1 --worksize 64 --intensity 11 --thread-concurrency 64" #NeoScrypt
}
