### ISSUE TITLE
Excavator Support

### ISSUE THREAD

**Issue by pokepud3** [Sniffdog/Sniffdogminer#24]
Using a 1070ti I can get 5% faster speeds using the excavator from nicehash software using MPM.. Any reason why we can't manually add support to add it in ?

https://github.com/nicehash/excavator/releases

With a 1070 ti I can pull 45MH using ccminer and sniffdog, and 50MH using ExcavatorNvidia2 or ExcavatorNvidia3 w/MPM.

**Comment by Sniffdog** [comment]
Sure I can look at it for you :) Which algo would you like to use it for?

**Comment by pokepud3** [comment]
I use this specifically for Lyra2rev2 but I read it's better for a few
other algorithms.  haven't compared it for those yet.

**Comment by Sniffdog** [comment]
ah ok I'll compare with ccminer palgin for speed then get back to you k?

**Comment by pokepud3** [comment]
Thanks, Appreciate the help :)

**Comment by Sniffdog** [comment]
WARNING!!! Excavator is a proprietary software by NiceHash and has a special EULA. YOU ARE NOT ALLOWED TO REDISTRIBUTE IT! Sorry can't help yah

**Comment by pokepud3** [comment]
multipoolminer v2 uses it, and gets around it by asking you to manually
drop it in. Dunno how hard it is to allow for the same.

**Comment by Sniffdog** [comment]
I do not like warning signs..... therefore I'm gonna leave it. Sorry

**Comment by pokepud3** [comment]
Thanks for considering it regardless.

**Comment by Sniffdog** [comment]
pokepud3... After looking at this long and reviewing the comments about other I might as well include excavator in the Miners folder. Yes you will have to manually move the files to the excavator folder under Bin folder....

**Comment by pokepud3** [comment]
that's awesome, let me know when I can run some tests!

**Comment by Sniffdog** [comment]
I have added the files you can download the master

**Comment by pokepud3** [comment]
Where would I put the excavator folder in?  Looking forward to having some fun testing these.

**Comment by Sniffdog** [comment]
if you download the master from the main github. It's already to go....

What happens in the Bin folder is that a double excavator folder is made... All you have to do is take the second folder file and place it into the first one.

**Comment by Sniffdog** [comment]
Everything seems to be running ok so I'll try it in a bigger rig.... the cpuminer may need to drop in threads... but I will monitor

**Comment by pokepud3** [comment]
Tested it out for a few hours and it's working great..

For the lyra2RE2 it's 52MH vs 45MH... which makes it more profitable to mine. Just curious if it's beneficial to up the interval time on my end to like 10-15 minutes to mine more complete shares?

**Comment by Sniffdog** [comment]
that is totally upto you... and I'm glad your excavator is working!

**Comment by Sniffdog** [comment]
Thank you so much and greatly appreciated BMR79 

Ahashpool is a great place to be mining and has excellent support!

We all just need to be patient when it comes to payments since the Bitcoin network congested, hardly anyone can get any transactions confirmed :)

**Comment by pokepud3** [comment]
There may be a difficulty setting issue somewhere with excavator, anytime
it runs im seeing an insane amount of shares, or is this normal for this?

https://imgur.com/FSxkYcE

**Comment by Sniffdog** [comment]
just had a chance to watch it.....

it was doing this on hashrefinery....could be the stratum diff is not changing at the pool therefore you will see a big number of shares go through....

Didn't do it on zpool

didn't do it on ahashpool

I also noticed before bed was that the pool api's were going down at ahashpool and at hashrefinery...

**Comment by pokepud3** [comment]
So I tried setting this up from scratch again, and it doesn't automatically download excavator anywhere in the files upon running of the startsniffin.bat or the newer ahashpool one. Anything i need to do manually to enable excavator support again? I don't see it in the bin folder either.

**Comment by Sniffdog** [comment]
you need to goto miners folder and remove the # in front of the algo 

![screenshot 35 _li](https://user-images.githubusercontent.com/30452757/35343123-0b6699e6-00e7-11e8-98c3-bd0ee02a53a5.jpg)

**Comment by pokepud3** [comment]
Awesome thanks, exactly what I was looking for! Thanks again.
