### ISSUE TITLE
Cryptonight not profitable for 10X0 Cards?

### ISSUE THREAD

**Issue by pokepud3** [Sniffdog/Sniffdogminer#26]
Just curious if there is a reason you left out the cryptonight algo from the original bat file? Is it not to profitable when it comes to nvidia cards or was there a conflict/bug within the miner?

**Comment by Sniffdog** [comment]
no cryptonight is there just turned off... At 90 sec benching it sometimes wouldn't work. All you have to do is add it to your startsniffin.bat and it's ready for you. You may need to increase benching to a higher interval( instead of 90 maybe 240 for that algo)
