### ISSUE TITLE
Getting some kind of JSON fetching issue

### ISSUE THREAD

**Issue by drew-wallace** [Sniffdog/Sniffdogminer#27]
Here's the error:
```
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\<username>\Documents\Sniffdogminer\SniffDog.ps1:95 char:135
+ ... or.com/api/ticker/btc-$_" -UseBasicParsing | ConvertFrom-Json).ticker ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

Looks like it doesn't like this line:

```
$Currency | ForEach {$Rates | Add-Member $_ (Invoke-WebRequest "https://api.cryptonator.com/api/ticker/btc-$_" -UseBasicParsing | ConvertFrom-Json).ticker.price}
```

Are you trying to hit this `https://api.cryptonator.com/api/ticker/btc-usd`?

I see, they switched it up and now load a JavaScript file that then calls the API. Sneaky...

**Comment by drew-wallace** [comment]
This URL should work in it's place:

```
https://api.gdax.com/products/BTC-USD/ticker
```

**Comment by Sniffdog** [comment]
I will try gdax thank you.... I just went through a complete diagnostic and didn't have this issue

**Comment by drew-wallace** [comment]
Weird. Maybe it was a hiccup with cryptonator...

**Comment by Sniffdog** [comment]
perhaps... the actual line I have is https://api.cryptonator.com/api/ticker/btc-$_

**Comment by drew-wallace** [comment]
I had that too, but I got an error with that one. Then I tried ending with usd and the data returned in the browser. But the same call from powershell gave me html. Gdax sent me the appropriately formatted json.

**Comment by Sniffdog** [comment]
Well I tried to get gdax api running... I'll keep on working on it. I replaced cryptonator and everything runs fine again with different currencies

**Comment by drew-wallace** [comment]
Yeah USD

**Comment by Sniffdog** [comment]
Looks like ahashpool repaired it....

 Write-host "Loading BTC rate from 'api.coinbase.com'.." -foregroundcolor "Yellow"
+    $Rates = Invoke-RestMethod "https://api.coinbase.com/v2/exchange-rates?currency=BTC" -UseBasicParsing | Select-Object -ExpandProperty data | Select-Object -ExpandProperty rates
+    $Currency | Where-Object {$Rates.$_} | ForEach-Object {$Rates | Add-Member $_ ([Double]$Rates.$_) -Force}

**Comment by Sniffdog** [comment]
https://github.com/ahashpool/Sniffdogminer/commit/127c378dc74af83cdbe558454f96e691c15e08e2
