### ISSUE TITLE
Miner is not working

### ISSUE THREAD

**Issue by mforce** [Sniffdog/Sniffdogminer#3]
I tried zpool and it does not set the address properly it shows empty on the miner. and it throws error when trying to connet.

**Comment by Sniffdog** [comment]
ok need more information ie: using a btc wallet address? because then passwordcurrency should be BTC as well

**Comment by mforce** [comment]
I tried it again same issue, attached a screenshot.
![screenshot](https://user-images.githubusercontent.com/3101827/29491138-17bec030-8507-11e7-9479-6ed3ddd53795.png)

**Comment by Sniffdog** [comment]
Can I check to see what you have in the startsniff.bat please.

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Username Tyredas -Workername Beeboop -Currency USD -Passwordcurrency BTC -interval 90 -Wallet 1AMQg6m9GPDN9HGuC3wJGpSuiZr1XQXjxi -Location US -PoolName zpool,hash,MPH -Type nvidia -Algorithm jha,tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,hmq1725,x17,blakecoin,cryptonight,lyra2z,timetravel -Donate 5

This is the default startsniff.bat.... you should have Your btc address and Your Miningpoolhub Username and Workername.... all of this should still be in your startsniff.bat. You can change Donate 0 if you wish not to donate

I downloaded the master as well last night and ran it completely with no issues...
