### ISSUE TITLE
Daily summary ?

### ISSUE THREAD

**Issue by ninox21** [Sniffdog/Sniffdogminer#30]
Hi Sniffdogminer ,
Is there any way to add or see how much you earn for last 24 hours ?
Thank you

**Comment by Sniffdog** [comment]
Well..... we usually leave that upto the clients that we have to view the mining pools and interact through online chat.

 We use Sniffdog primarily for data. Maybe in the near future we may add more features but right now we are trying to keep it as a "light-end" software program capable of running 26 different algos(for now) with min downtime once the mining rig software is installed. 

Maybe in 2018 there will be more added features, I know I'm not going anywhere while the crypto rush is on! :)
