### ISSUE TITLE
EWBF Failed and stop Benchmarking.

### ISSUE THREAD

**Issue by sumate-k** [Sniffdog/Sniffdogminer#31]
Sniffdogminer2.8 
every time Benchmarking, it's Failed and stop.
  
 Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-EWBF\Zminer.exe --api --server  --port  --fee 0 --solver 0 --eexit 1 --user
                                               --pass

**Comment by Sniffdog** [comment]
did you exempt the folder from your antivirus?

**Comment by sumate-k** [comment]
I set Exclusions Windows Defender Antivirus in folder already.

**Comment by Sniffdog** [comment]
ok in the stat folder you will see ewbf hashrate stats ... you need to delete that Sniffdog regected it

**Comment by Sniffdog** [comment]
If all that doesn't work.... I will include a "manual" setup for excavator and equihash.... I did have a open ticket about how others were telling to use excavator and to manually install the files....

So make sure you get back to me

**Comment by sumate-k** [comment]
OK. It's works.

Thank you very much.

**Comment by sumate-k** [comment]
ahashpool.com not have algo Equihash.

**Comment by Sniffdog** [comment]
Np I'm always checking here often....
