### ISSUE TITLE
Incorrect hash speed values after benchmarking

### ISSUE THREAD

**Issue by shhyguuy** [Sniffdog/Sniffdogminer#32]
Today when I got home I noticed my estimated earnings are crazy all over the place. CCminerpalgin on ahashpool showing 35,000.00 USD per day, CCminerpoly on zpool showing 2,400.00 USD per day.

I deleted all files in Stats and after another benchmark it still shows up with bogus values.

**Comment by Sniffdog** [comment]
ok so ccminerpalgin runs lyra2RE2... and I'm assuming the poly ccminer was poly?

Also, which version are you using and did you download your Sniffdog from here.

Another  is that I added excavator as a manual install.... you can find support in #24 issue for lyra2RE2

I will go in and see if a patch is needed at zpool and at ahashpool for stats.... sometimes they do work on their end without telling anyone

Thanks for letting me know.  you will have to download the master at github since excavator is not in the releases yet... I also added cpu as well

**Comment by shhyguuy** [comment]
I'm not sure what's up with mine. I'm using 3.0 downloaded from here on releases tab, didn't download the master with excavator yet.

Here is what I'm getting:

<img width="622" alt="2017-12-19 21_38_41-select c__windows_system32_cmd exe" src="https://user-images.githubusercontent.com/15005522/34192801-13c1aa98-e505-11e7-873d-a1d12e1137c8.png">

**Comment by Sniffdog** [comment]
yeah that is weird esp when they are all in GH

**Comment by shhyguuy** [comment]
I cloned the master into a new folder and it's working fine now. Almost done benchmarking the algos and everything looks normal. Thanks!

**Comment by Sniffdog** [comment]
Awesome! 

Note: even the cpuminer is manual. Add in startsniffin.bat nvdia,cpu then yescrypt as an algo

**Comment by frederikvanduuren** [comment]
Sniffdog,

would you be willing to share/publish your personal startsniffin.bat file for us?

thanx

fred

**Comment by Sniffdog** [comment]
Sure fred,

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Username Tyredas -Workername Beeboop -Currency USD -Passwordcurrency BTC -interval 240 -Delay 2 -Wallet 1AMQg6m9GPDN9HGuC3wJGpSuiZr1XQXjxi -Location US -PoolName zpool,hash,ahashpool,mph -Type nvidia,cpu -Algorithm phi,hsr,xevan,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,x11evo,veltor,blake2s,hmq1725,x17,lyra2z,timetravel,polytimos,cryptonight,keccak,yescrypt,tribus,decred,ethash -Donate 5

only changes I made over the holidays was removing Tribus and always run my interval at 240 and delay 2

Hope that helps.... please don't ask me why... it's just my preference :)

**Comment by frederikvanduuren** [comment]
wow thanx for sharing :)

how did you setup your auto exchange on MPH?

thanx for all u do

fred

**Comment by Pryometrix** [comment]
Hey Sniffdog welcome back and Happy New Year. Just curious I noticed you and a few other users mentioned they removed Tribus over the holidays, just curious if that is still suggested to do or is it ok that I haven't removed it and just to leave it as is?

**Comment by Sniffdog** [comment]
It's upto you... I was just noticing Tribus as a "outlier" than a profit maker.

What I mean is... how could the price jump so high then crash down to nothing.... 

the "con" to all this????? If a pump does happen in Tribus... how would you know?

**Comment by Sniffdog** [comment]
@frederikvanduuren well that is simple and inside Miningpoolhub... you make sure you goto auto exchange and have it set for.... ( I chose bitcoin) and then click on bitcoin in the mining section and add your wallet address. You can also have your settings for minimum payouts too

**Comment by frederikvanduuren** [comment]
@Sniffdog MPH is setup, just curious if its better to get each coin seperatly?
vs "not set"
now i use LTC as default ;)

**Comment by Sniffdog** [comment]
I use bitcoin for my clients :)

until the world makes it completely impossible to have bitcoin... I'll keep using it

**Comment by Pryometrix** [comment]
Thanks again Sniffdog, just wondering how I would go about sending donations to you for all the work you do and to help with future support. 

Would I just send bitcoin to your address mentioned above or do you have a PayPal address for donations? I know the default in the Sniffdogminer for donations is 5 minutes/day and can be set higher, but this way I can actually donate specific dollar amounts to you.

**Comment by Harileu** [comment]
@Sniffdog Thanks for helping, but there is still a problem with MPH-Feathercoin calculation... it says something like about 500 dollars a day... but this is just 100 times too much. how can one adjust it to the right amount of about 5 dollar a day? (btw 1080ti card). Thanks in advance!
