### ISSUE TITLE
Adding Nicehash

### ISSUE THREAD

**Issue by cryptomandingus** [Sniffdog/Sniffdogminer#34]
seeing as snifferdogminer now uses excavator as a miner, is there anyway that Nice-hash could be added in as a pool option? 

I assume that its a lot of work, however I thought I would just ask the question.

**Comment by Sniffdog** [comment]
Haha yes excavator is hiding inside of Sniffdog but if you notice when you download and run Sniffdog... excavtor will not show up... so technically we are not using excavator in the lineup...
