### ISSUE TITLE
Merry Christmas and Happy New year...I'll be leaving for holidays and won't be back till the New Year!! 

### ISSUE THREAD

**Issue by Sniffdog** [Sniffdog/Sniffdogminer#35]

**Comment by luk3r88** [comment]
Merry Christmas und Happy New Year to you too mate. Thanks for the nice work you have done so far

**Comment by meyerbro** [comment]
Yes, thanks for this nice work, really appreciated.

**Comment by Pryometrix** [comment]
Merry Christmas to you too, thank you for everything seriously your program is awesome! I encourage those who don't to make sure to donate a minimum of 5 minutes a day, this developer deserves it and it only helps us in the end, plus it's Christmas 🎄 lol.

**Comment by lazaac** [comment]
Happy New Year to you too..

**Comment by Sniffdog** [comment]
Thank you everyone... Today is the first day of the new week of the new month of the new year... let's make a difference shall we? :)

**Comment by frederikvanduuren** [comment]
I wish you to be yourself x

**Comment by Sniffdog** [comment]
🥇
