### ISSUE TITLE
Trying to add custom sp mod miner

### ISSUE THREAD

**Issue by DangerD256** [Sniffdog/Sniffdogminer#36]
Trying to add custom miner, i've made a copy of CcminerTpruvot.ps1 and called CcminerSp-mod-phi.ps1
Changed path and commented out everything except PHI
```
$Path = ".\Bin\NVIDIA-SP-PHI\ccminer-phi-sp1.exe"
$Uri = 'http://'

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Algorithms = [PSCustomObject]@{
    #Lyra2z = 'lyra2z'
    #Equihash = 'equihash' #not supported
    #Cryptonight = 'cryptonight'
    #Ethash = 'ethash' #not supported
    #Sia = 'sia'
    #Yescrypt = 'yescrypt'
    #BlakeVanilla = 'vanilla'
    #Lyra2RE2 = 'lyra2v2'
    #Skein = 'skein'
    #Qubit = 'qubit'
    #NeoScrypt = 'neoscrypt'
    #X11 = 'x11'
    #MyriadGroestl = 'myr-gr'
    #Groestl = 'groestl'
    #Keccak = 'keccak'
    #Scrypt = 'scrypt'
    #Bitcore = 'bitcore'
    #Blake2s = 'blake2s'
    #Sib = 'sib'
    #X17 = 'x17'
    #Quark = 'quark'
    #Hmq1725 = 'hmq1725'
    #Veltor = 'veltor'
    #X11evo = 'x11evo'
    #Timetravel = 'timetravel'
    #Blakecoin = 'blakecoin'
    #Lbry = 'lbry'
    #Jha = 'jha'
    #Skunk = 'skunk'
    #Tribus = 'tribus'
    Phi = 'phi'
    #Hsr = 'hsr'
}

$Optimizations = [PSCustomObject]@{
    Lyra2z = ' --api-remote --api-allow=0/0'
    Equihash = ''
    Cryptonight = ' --api-remote --api-allow=0/0'
    Ethash = ''
    Sia = ''
    Yescrypt = ''
    BlakeVanilla = ''
    Lyra2RE2 = ''
    Skein = ''
    Qubit = ''
    NeoScrypt = ''
    X11 = ''
    MyriadGroestl = ''
    Groestl = ''
    Keccak = ''
    Scrypt = ''
    Bitcore = ' --api-remote --api-allow=0/0'
    Blake2s = ''
    Sib = ''
    X17 = ''
    Quark = ''
    Hmq1725 = ' --api-remote --api-allow=0/0'
    Veltor = ''
    X11evo = ''
    Timetravel = ' --api-remote --api-allow=0/0'
    Blakecoin = ''
    Lbry = ''
    Jha = ' --api-remote --api-allow=0/0'
    Skunk = ' --api-remote --api-allow=0/0'
    Tribus = ' --api-remote --api-allow=0/0'
    Phi = ' --api-remote --api-allow=0/0'
    Hsr = ' --api-remote --api-allow=0/0'
    
}

$Algorithms | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name | ForEach {
    [PSCustomObject]@{
        Type = 'NVIDIA'
        Path = $Path
        Arguments = -Join ('-a ', $Algorithms.$_, ' -o stratum+tcp://$($Pools.', $_, '.Host):$($Pools.', $_, '.Port) -u $($Pools.', $_, '.User) -p $($Pools.', $_, '.Pass)', $Optimizations.$_)
        HashRates = [PSCustomObject]@{$_ = -Join ('$($Stats.', $Name, '_', $_, '_HashRate.Week)')}
        API = 'Ccminer'
        Port = 4068
        Wrap = $false
        URI = $Uri
    }
}
```

And i'm getting this:
```
Invoke-Expression : At line:1 char:20
+ "$($Stats.CcminerSp-mod-phi_Phi_HashRate.Week)"
+                    ~~~~
Unexpected token '-mod' in expression or statement.
At line:1 char:24
+ "$($Stats.CcminerSp-mod-phi_Phi_HashRate.Week)"
+                        ~~~~~~~~~~~~~~~~~
Unexpected token '-phi_Phi_HashRate' in expression or statement.
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\Include.ps1:149 char:40
+ ...                $Property.$_ = Invoke-Expression "`"$($Property.$_)`""
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand

Cannot convert value "$($Stats.CcminerSp-mod-phi_Phi_HashRate.Week)" to type "System.Double". Error: "Input string was not in a correct format."
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\SniffDog.ps1:167 char:13
+             $Miner_HashRates | Add-Member $_ ([Double]$Miner.HashRate ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToDoubleOrSingle

Cannot convert value "$($Stats.CcminerSp-mod-phi_Phi_HashRate.Week)" to type "System.Double". Error: "Input string was not in a correct format."
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\SniffDog.ps1:170 char:13
+             $Miner_Profits | Add-Member $_ ([Double]$Miner.HashRates. ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToDoubleOrSingle

Cannot convert value "$($Stats.CcminerSp-mod-phi_Phi_HashRate.Week)" to type "System.Double". Error: "Input string was not in a correct format."
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\SniffDog.ps1:171 char:13
+             $Miner_Profits_Comparison | Add-Member $_ ([Double]$Miner ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToDoubleOrSingle

Cannot convert value "$($Stats.CcminerSp-mod-phi_Phi_HashRate.Week)" to type "System.Double". Error: "Input string was not in a correct format."
At C:\Users\Miner\Desktop\Sniffdogminer-2.8.A\SniffDog.ps1:172 char:13
+             $Miner_Profits_Bias | Add-Member $_ ([Double]$Miner.HashR ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToDoubleOrSingle

```
What i've missed?

**Comment by frederikvanduuren** [comment]
i guess different API...

**Comment by nemosminer** [comment]
correct it sp-mod API issue run it as WRAPPER same as the sp-mod .ps1 you already have 
eg.   

        API = "Wrapper"
        Port = 4068
        Wrap = $true
        URI = $Uri
    }
}

**Comment by Sniffdog** [comment]
actually nemo no it doesn't need wrapper...

please delete what you did and use the sp-mod that is in the miners folder and add....

Phi = 'phi' (in algorihtms)

and 

Phi = ''  (in Optimizations)

What you did Danger is take Tpruvot miner... just us the sp-mod miner file.... add these lines of code and it will auto download and run for you... if Phi doesn't show up on Sniffdog in sp-mod then sp-mod doesn't support it

**Comment by DangerD256** [comment]
I need to use another sp mod (paid one optimized for phi)

**Comment by Sniffdog** [comment]
oh goodness! I see now what you are trying to do!

No let this one download so it makes a bin folder for sp-mod then just copy the one you paid for into that bin folder... make sure it has the same name so it will run in sniffdog

**Comment by DangerD256** [comment]
I have several ccminers, each one for each algo, so I need some template so I can copypaste config to use several ones

**Comment by DangerD256** [comment]
http://files.dangerd.org/pub/!PUBLIC//Screenshot_2018-01-01-16-40-51.png

**Comment by Sniffdog** [comment]
yes just rename the CcminerSp-mod.ps1 to the next ccminer you have ( ie. CcminerSp-phi.ps1) 

Sniffdog will auto bench.... to clean up... just turn off the "doubles" in the other .ps1 miners folder

**Comment by DangerD256** [comment]
Check screenshot in previous screenshot

**Comment by Sniffdog** [comment]
yeah see tpruvot has different optimization factors than sp-mod.. You should be using the sp-mod that is dormant in the miners folder.... take off the optimization and leave it as ''

**Comment by DangerD256** [comment]
Just downloaded latest version, changed config file to use only ahashpool and got this:
![image](https://user-images.githubusercontent.com/17032489/34557672-baa1b91c-f143-11e7-9079-edd28480139b.png)
If algo doesn't exists on pool scripts runs miner with empty pool url and wallet, that's should be fixed, had to remove algos from bat file.
Regarding miner for phi, can't get it work:
http://files.dangerd.org/pub/Mining/ccminer-phi-sp1.zip
You can take it from here
Non working config:
http://files.dangerd.org/pub/Mining/CcminerSp-mod-phi.ps1

**Comment by Sniffdog** [comment]
Sorry but we at Sniffdog always prepare ourselves for the worst case scenario...

Did you know Sniffdog runs 3 yimp pools and one nomp pool? What happens if the yimp pools go down when your partying at Bora Bora? :)

Don't think this does not happen because back in august/september we had all the yimp pools go down due to a hack... the only one that worked was Miningpoolhub.

**Comment by DangerD256** [comment]
Config file I tried to create by myself...
Any suggestion what I should change?

**Comment by Sniffdog** [comment]
yeah download my master https://github.com/Sniffdog/Sniffdogminer

just add to CcminerSp-mod.ps1 in Miners folder:

$Path = ".\Bin\NVIDIA-SP-PHI\ccminer-phi-sp1.exe"
$Uri = 'http://files.dangerd.org/pub/Mining//ccminer-phi-sp1.zip'

and remove the # in front of phi

**Comment by DangerD256** [comment]
Downloaded latest from master, changed to that strings, added Phi = 'phi'  (not existed before)
Now i'm getting this:
![image](https://user-images.githubusercontent.com/17032489/34581845-9795f094-f19a-11e7-9240-fd6ed18935ef.png)

**Comment by Sniffdog** [comment]
thanks then i can help with this

**Comment by DangerD256** [comment]
Also this issue with blank pool url/wallet
Default command line (just changed credentials)
`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Username DangerD -Workername MinerHome -Currency USD -Passwordcurrency BTC -interval 90 -Delay 1 -Wallet 1G45fZkjKcj6HwCzVe3bK1KRLtJRQSNkWQ -Location US -PoolName ahashpool,zpool,hash,MPH -Type nvidia,cpu -Algorithm phi,hsr,xevan,tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,hmq1725,x17,lyra2z,timetravel,polytimos,ethash,decred,yescrypt -Donate 5`

And script runs:
`Bin\NVIDIA-TPruvot\ccminer-x64.exe -a decred -o stratum+tcp://: -u  -p  --api-remote --api-allow=0/0`

What i've missed?

**Comment by Sniffdog** [comment]
you missed nothing.... that showed that the pools api was down at the time you benched...

**Comment by DangerD256** [comment]
thanks, works now.
Personally i didn't paid for it, but developer can be upset if you will distribute for everybody =)

**Comment by Sniffdog** [comment]
yeah i don't need SP on my A## haha
