### ISSUE TITLE
Payouts

### ISSUE THREAD

**Issue by Raythe3** [Sniffdog/Sniffdogminer#38]
Something weird is going on.  Hashrates are the same, payouts are way down.  Going to have to switch pools or limit the algo's used.  X17 seems ok, but others are just crazy low.

Not sure if I'm reading this right, but below is an example.  The payout for GoByte seems right, but Guncoin seems to be at a fraction.

  | Guncoin (neoscrypt) | 0.087794 GUN | 0.059% | 0.00000002 | 53m ago 
  | GoByte (neoscrypt) | 0.003828 GBX | 0.051% | 0.00000470 | 57m ago

The last 24 hours have been brutal, down from $40 per day to around $10.

**Comment by jayntguru** [comment]
where?

**Comment by frederikvanduuren** [comment]
Hi,

I have the same low mining earnings lately :( from $50/day to $15/day!

any ideas what changed after the last upgrade?
fred

**Comment by cryptomandingus** [comment]
I think it is to do with the pools mining bad coins, for example if you are mining: 

Verge (x17) | 0.681762 XVG | 0.044% | 0.00000537
-- | -- | -- | --
comparing this to one of the bad coins

Denarius (tribus) | 0.005487 DNR | 0.183% | 0.00000029
-- | -- | -- | --

this continues

AuroraCoin (skein) | 0.001561 AUR | 0.062% | 0.00000015
-- | -- | -- | --

I think for the time being it might be best just to turn off all other algorthims bar, x17, lyrare2, equihash,

**Comment by Raythe3** [comment]
Yeah, there are some downright horrible coins that are being mined that are linked to faulty profit calculations.  AuroraCoin (Skein) is one of them, however Digibyte (skein) seems to be ok.  I'm assuming that Skein will mine either of those coins along with Unitis (another crappy to BTC conversion rate).  I still have more to learn but Unitis was also used for PHI and was garbage there too, but Luxcoin seemed normal for PHI.

Me and a friend have removed Tribus (Denarius) and that has improved things dramatically.  Still no where near what it was a couple of weeks ago, but much closer to the current profit algo claims.

On a side note, not sure if Sniffdog is going to look at a 24 hour profit algo in the future.   I like his scripting better than Nemos (obviously they quite similiar) and ahash seems like a much better pool than the others I've used.

**Comment by frederikvanduuren** [comment]
i agree too many crappy new coins/algos...
would be good to report the shitty ones here? :)

**Comment by frederikvanduuren** [comment]
I just kept: NIST5, KECCAK, CRYPTONIGHT, NEOSCRYPT, LYRA2R2 & EQUIHASH

its doing even worse than before :(

Any ideas? tweaks?

fred

**Comment by Sniffdog** [comment]
Yes the whole trick is to.... set it and forget it....

shitcoins pump and dumps are common and with Sniffdog running on so many algos... we are bound to find those pumps...
