### ISSUE TITLE
Skunk speed is very low on 1080ti

### ISSUE THREAD

**Issue by EvilMonkeyTurds** [Sniffdog/Sniffdogminer#4]
Skunk miner speed is very low.  I get 45 1080ti with sniffdog. @ 85% TPD

I can get 55 MH/s @ 85% tpd with the below miner.  Also Palg has a miner that is about 54 MH/s
https://github.com/tpruvot/ccminer/releases

**Comment by Sniffdog** [comment]
Yes for the more advanced users that wish to overclock their systems.... you can Edit (right click then edit) the powershell files in Miners and enable/disable algos by simply adding/removing the # in front of the algo.

I have added all updated ccminers in the miners folder if you wish to play with which ccminer is best for you....

Sniffdog is a stock product.. Sniffdog runs smoothly as is... What you do with it is your choice :)

**Comment by Sniffdog** [comment]
re benched Sniffdog after new ccminer updates came online
