### ISSUE TITLE
sniffdog support EthMonitoring？

### ISSUE THREAD

**Issue by Jacky1202** [Sniffdog/Sniffdogminer#41]
thx for help :)

**Comment by frederikvanduuren** [comment]
i use both just setup your pool types + wallets ;)

**Comment by Sniffdog** [comment]
Happy New Year

Yes i use this for my biggest client to monitor watts plus temp on the rig

if ethmonitor doesn't show anything on ethmonitor app... it's because the miner has not been implemented to ethmonitor...  Sniffdog runs a lot of algos...
