### ISSUE TITLE
CCminer Errors - Nvidia-Poly & TPRuvot

### ISSUE THREAD

**Issue by russellt83** [Sniffdog/Sniffdogminer#45]
CCminer Nvidia-Poly & TPruvot are not running correctly. 

![capture1](https://user-images.githubusercontent.com/35022007/34475437-3ef7e764-efe0-11e7-86e6-11149a27a24c.JPG)
![capture2](https://user-images.githubusercontent.com/35022007/34475440-40a64858-efe0-11e7-8fe2-1fed16feb5d2.JPG)

**Comment by russellt83** [comment]
Just realised its probably because i only use mph and they might not have coins for those algos.

**Comment by Sniffdog** [comment]
yeah it's not showing the pool address

that is the site API issue... give it time and try again

**Comment by lazaac** [comment]
Sorry just asking, how long will it takes to just benchmark all those algo using just one 1080Ti?

**Comment by Sniffdog** [comment]
the default startsniffin.bat has your interval set at 90 sec per bench. there are 29 possible algos in the startsniffin.bat so 90 sec times 29 = 2,610 secs or divide by 60 = approx 44 minutes...

This is for all... no matter how many cards you have...
