### ISSUE TITLE
Diable 1 GPU

### ISSUE THREAD

**Issue by abinsraj** [Sniffdog/Sniffdogminer#46]
Hi Guys can anyone help me how to disable one of my GPU in sniffdog

**Comment by Sniffdog** [comment]
I'll be working on that this week if you can wait?

**Comment by Sniffdog** [comment]
ok goto splitsniff and download the master copy 

https://github.com/Sniffdog/SplitSniff

In the startsniffin.bat change the (-SplitSniffCC '0,1,2,3' -SplitSniffEWBF '0 1 2 3') to your designated GPU(s) in which you want to use...

SplitSniffCC is for Ccminers and SplitSniffEWBF is for equihash (see how the comma is used in Ccminer)

Excavator,Cpuminer, and duelminer are not added to splitsniff at this time... but at least you can get up and running with your card(s)

**Comment by abinsraj** [comment]
@Sniffdog thanks man it helped me. Thankyou so much!!

**Comment by abinsraj** [comment]
I use sniffdog in ahashpool.

**Comment by Sniffdog** [comment]
you may have errors if you leave out the other pools while benching.... this is normal since we keep other pools in case for backup...

just bench the algos you wish to mine in ahashpool in your startsniffin.bat

**Comment by abinsraj** [comment]
@Sniffdog I downloaded splitsniff master copy and benched and it worked fine for couple of hours. But now system crashes and rebooting. Did I do anything wrong?

**Comment by abinsraj** [comment]
@Sniffdog There is no file named startsniffin.bat in splitsniff master copy.

**Comment by Sniffdog** [comment]
splitsniffin.bat and no you didn't do anything wrong unless you are trying to overclock
