### ISSUE TITLE
last refresh

### ISSUE THREAD

**Issue by jayntguru** [Sniffdog/Sniffdogminer#47]
I just added this piece of code manually. Nice update.

https://github.com/nemosminer/NemosMiner-v2.3/commit/e0693778fd83e5995c07a8cc78c16b8e82e71c95

**Comment by jayntguru** [comment]
Actually it goes before the sleep. that code isn't right. but you get the idea.

**Comment by Sniffdog** [comment]
Thank you jayntguru I shall test this today :)

**Comment by Sniffdog** [comment]
I have placed your line of code just after coinbase API check and am testing... so far no errors have been found

**Comment by Sniffdog** [comment]
}
    Write-host "Loading BTC rate from 'api.coinbase.com'.." -foregroundcolor "Yellow"
    $Rates = Invoke-RestMethod "https://api.coinbase.com/v2/exchange-rates?currency=BTC" -UseBasicParsing | Select-Object -ExpandProperty data | Select-Object -ExpandProperty rates
    $Currency | Where-Object {$Rates.$_} | ForEach-Object {$Rates | Add-Member $_ ([Double]$Rates.$_) -Force}
    Write-Host -ForegroundColor Yellow "Last Refresh: $(Get-Date)"

**Comment by Sniffdog** [comment]
Logs folder is picking up the timestamp... Nice work!

**Comment by jayntguru** [comment]
I didn't write it, I just copied it. :)

**Comment by Sniffdog** [comment]
Made me chuckle.... make sure you let the author know

**Comment by Sniffdog** [comment]
i did talk to the author of this code and he has allowed us to place into Sniffdog!!!

Nice little one line of code that adds a time stamp for refreashing

Look at the time timestamp from last refresh(top left) to the clock at (bottom right)...


![screenshot 7](https://user-images.githubusercontent.com/30452757/34575438-0aa0e7be-f138-11e7-8663-b667af928ca7.png)

**Comment by jayntguru** [comment]
Dude you're gonna be rich.

**Comment by Sniffdog** [comment]
haha! I wish SIB would pay me like that! I was able to pickup an issue and prove it with a timestamp
