### ISSUE TITLE
Difficulty set optimum for 1080 Ti - for each algorithm?

### ISSUE THREAD

**Issue by KorDen1977** [Sniffdog/Sniffdogminer#49]
Make "Difficulty" for each algorithm - optimum for 1080 Ti!
And still it is possible to make "coefficient" for more feeble GPU relatively - difficulties of 1080 Ti.

For example command: -p d=48

P.S.
Otherwise the miner does not get on well at the auto will be set up on really profitable difficulty... and a favor of switching from an algorithm to an algorithm can just not be.

**Comment by Sniffdog** [comment]
ahashpool does not like dif... in fact if peeps set to low they will get banned

**Comment by KorDen1977** [comment]
And the problem in "space" can - the command shall be conjoint, partitioned ","?
-p d=30,c=XVG

**Comment by Sniffdog** [comment]
Yeah if you want XVG you can change -Passwordcurrency BTC  to  -Passwordcurrency XVG in startsniffin.bat and make sure -Wallet your_XVG_public_address_goes_here

As far as changing stratum diff... you will have to manually go in and change it at the Miners folder.

**Comment by KorDen1977** [comment]
Then why the written difficulty Works as me? -p d=0.158,

Bin\NVIDIA-TPruvot\ccminer-x64.exe -a phi -o stratum+tcp://phi.mine.ahashpool.com:8333 -u 1CYRTNJmiJQVZ1s9rs8Us1ghqvwMY4vYed -p d=0.158,ID=worker001,c=BTC --api-remote --api-allow=0/0

**Comment by Sniffdog** [comment]
You must be one of the lucky ones!

please explain how you did this?

**Comment by KorDen1977** [comment]
:)
I copied the start line "startsniffin", the Phi algorithm, saved in .bat
And simply - I added the parameters of "difficulty" to the .bat file.
And launched ...

**Comment by Sniffdog** [comment]
Ok... so you are only mining on the yimp pools that sniffdog uses?

**Comment by KorDen1977** [comment]
Yes!

**Comment by Sniffdog** [comment]
Awesome I'm glad it worked for you and maybe for others that see this thread. 

Just be careful... Ahashpool has already put out a warning saying they will ban addresses if diff is to low

Also got the startsniffin.bat and change -Passwordcurrency to_what_your_mining

Good luck!

**Comment by KorDen1977** [comment]
So more often - it makes a sense to increase "complexity"!
It shall be favorable to a pool!

And in those cases where it is necessary to reduce - I think that the pool just did not optimize parameters of difficulty of an algorithm!

Only if mining for 1050 or 1060 - and look for low difficulty for the feeble equipment, here the pool can ban.
In my case of 1080 Ti - its power is not present a sense to ban, even on very low difficulty!

**Comment by Sniffdog** [comment]
I know and it's ok to vent here :)

I don't make the rules... I just inform and update my software :)

**Comment by Sniffdog** [comment]
Hi....

Just to inform you that Hashsynminer has been released...

If you have been playing around with Sniffdog and know how to add or remove intensities.... good

This cures mixed rigs... you can add settings to each card in your mining rig...Hashsyn works for gen 10 nvidia cards...

I understood what you were talking about... I myself have a mixed rig and to try to set one intensity for all was not very good...

**Comment by YagerD** [comment]
Is there any write ups explaining how to set different Intensities for different algorithms in different versions of CC miner?
