### ISSUE TITLE
Decred Error

### ISSUE THREAD

**Issue by joesixpack** [Sniffdog/Sniffdogminer#51]
Stuck in a loop.  Had to comment out to get the benchmark to continue.

![image](https://user-images.githubusercontent.com/23145642/34581931-118d0daa-f147-11e7-8c88-152ea3be7d45.png)

**Comment by Sniffdog** [comment]
DangerD256 just pointed that out too... looks like zpool removed it... I have removed it from the startsniffin.bat

Thanks!

**Comment by Sniffdog** [comment]
new version created with updates

**Comment by joesixpack** [comment]
Veltor too.

**Comment by Sniffdog** [comment]
No Veltor is running .... but just at Zpool
