### ISSUE TITLE
2 little ideas 

### ISSUE THREAD

**Issue by snegrom** [Sniffdog/Sniffdogminer#53]
first sorry for my bad english 

the ideas:

1. status running --> is it possible to show the start time of the algo/coin running perhaps with endtime 

2. status idle --> is it possible to show complete time for each pool so its easyer to calculat profit per time per pool

i know both only comfort features  but if its easy to code it makes your real great dog a little bit more easy to use whitout to much work i hope 

thanks sneg
  
ps: idea3 ^^ dont know if its real good idea but .... benchmark only short therms 90 by default i use 300 for some algos(x17 usw). 
in "mining trim" i use 600-900 (10-15min) dont know if this is good still testing .
is it possible to update benchmark hashrate with real mining hashrate in mining trim? perhaps with a switch -updatebench yes/no.

**Comment by Sniffdog** [comment]
Placing it on the "to do" list...

default 90 is only for benching... what you mine with after is upto you and Sniffdog will follow along by auto updating the benchmarks...
