### ISSUE TITLE
CCminer stopped working with following error.

### ISSUE THREAD

**Issue by vishwajeetc** [Sniffdog/Sniffdogminer#54]
CCminer stopped working with following error, a window popup box comes up and miner doesn't do anything until I hit close program which means miner can be sitting idle for few hours.

Below error happened when phi algorithm was running on zpool, it has happened multiple times and I'm using 3.4

ERROR DETAILS 
--------------------------------------------------------------------

Faulting application name: ccminer.exe, version: 2.2.4.0, time stamp: 0x5a4e698b
Faulting module name: ccminer.exe, version: 2.2.4.0, time stamp: 0x5a4e698b
Exception code: 0xc0000005
Fault offset: 0x0000d832
Faulting process id: 0xeac
Faulting application start time: 0x01d3875b9bb76756
Faulting application path: C:\Users\Jeet\Downloads\Sniffdogminer3.4\Sniffdogminer-master\Bin\NVIDIA-TPruvot\ccminer.exe
Faulting module path: C:\Users\Jeet\Downloads\Sniffdogminer3.4\Sniffdogminer-master\Bin\NVIDIA-TPruvot\ccminer.exe
Report Id: e516ec52-443d-4568-95fd-d6bda603557d
Faulting package full name: 
Faulting package-relative application ID: 
------------------------------------------------------------------------------

**Comment by Sniffdog** [comment]
Strange.... that's a fresh version of Tpruvot 2.2.4...

Also noticing issues with Zpool that could cause a miner to crash...


![screenshot 9](https://user-images.githubusercontent.com/30452757/34646568-f048ef5e-f328-11e7-8546-36604423161e.png)

**Comment by Sniffdog** [comment]
yup all my rigs just had the same error at Zpool.... time to remove Zpool from the list until Zpool gets back to normal... Thanks for the heads up!
