### ISSUE TITLE
Benchmarks fail if you remove certain pools

### ISSUE THREAD

**Issue by mullen1200** [Sniffdog/Sniffdogminer#55]
I noticed with the latest build of sniffdog that there was no stratum address when I was getting stratum authentication errors. I only use Ahashpool. I had to use all pools, mph,hash,ahashpool,zpool, let the benchmarks finish, then remove the pools again. This requires a valid MiningPoolHub username. 
Removing the algorithms such as polytimos and x11evo from the startsniffin.bat did NOT fix the problem, I still had to benchmark them.

**Comment by Sniffdog** [comment]
mullen... I know... a lot of people want to use only one pool and have no backup while they are on holidays or work far away from home...

Please I don't want to be adding more confusion... just take a screenshot of ahashpools algos and remove the ones that are not on your screenshot from startsniffin.bat then everything will work fine

**Comment by mullen1200** [comment]
I know everything will work fine, I fixed it. I posted this so other users with the same problem will know how to fix it. It wasn't obvious to me and cost me a lot of time.

**Comment by mullen1200** [comment]
I just want to remind you that just removing the Algos won't work if it's their first time using sniffdog. It tries to Benchmark the remove Algos anyways.

**Comment by mullen1200** [comment]
And gets an error of course
