### ISSUE TITLE
I will add individual startsniffin.bat for ahashpool in next update

### ISSUE THREAD

**Issue by Sniffdog** [Sniffdog/Sniffdogminer#56]
For those miners who wish to use an individual pool... I will place example startsniffin.bat files in the next update...

**Comment by BMR79** [comment]
Lots of activity at zpool this AM, not for the good. Currently disabled it by removing from startsniffin.bat, hopefully they can get things resolved in a timely fashion.  Lots of upset miners on the discord forum. Ahashpool i've been finding has been mining 80% of the total anyways. Rarely a hit with multipoolhub also. Really glad to be apart of the pool at ahashpool. And really enjoy using sniffdogminer.

**Comment by Sniffdog** [comment]
Thank you.. a good word is always appreciated!

**Comment by mullen1200** [comment]
I'd like to say thanks as well. Keep up the great work

**Comment by Sniffdog** [comment]
+powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Workername Miner001 -Currency USD -interval 300 -Delay 1 -Wallet 1AMQg6m9GPDN9HGuC3wJGpSuiZr1XQXjxi -Location US -PoolName ahashpool -Type nvidia -Algorithm blake2s,MyriadGroestl,skein,x17,neoscrypt,sib,Lyra2RE2,xevan,tribus,phi,hsr,Nist5,groestl,lbry

This was placed into Sniffdog and it's from ahashpool Sniffdog which was updated today. Ahashpool also updated Pools/ahashpool.ps1file as well so this has also been placed into Sniffdog's update

**Comment by joeyroman84** [comment]
the ahashpool.bat doesn't work for me.  also no donation option in it?

**Comment by Sniffdog** [comment]
Thanks for the catch... I also added yescrypt, m7m, and opened lyra2h in cpuminer

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Workername Beeboop -Currency USD -Passwordcurrency BTC -interval 90 -Delay 1 -Wallet 1AMQg6m9GPDN9HGuC3wJGpSuiZr1XQXjxi -Location US -PoolName ahashpool -Type nvidia,cpu -Algorithm blake2s,MyriadGroestl,skein,x17,neoscrypt,sib,Lyra2RE2,xevan,tribus,phi,hsr,Nist5,groestl,lbry,yescrypt,m7m -Donate 5
