### ISSUE TITLE
Json error, zminer wont run/benchmark.

### ISSUE THREAD

**Issue by mullen1200** [Sniffdog/Sniffdogminer#58]
I reset my benchmarks, then went to sleep. I came back to a windors error "bad module info", and zminer was on repeat trying to benchmark. The zminer cmd window would NOT appear.  

I updated to your latest sniffdogminer, and same error.

I'm not sure whats wrong

At C:\sniffdogminer\Sniffdogminer-master\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: Rar.
At C:\sniffdogminer\Sniffdogminer-master\Include.ps1:127 char:42
+            $Content = $_ | Get-Content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by joeyroman84** [comment]
When that happened to me I just exited out and restarted and it fixed itself. Had to do it multiple times once but once all benchmarked all worked fine.

**Comment by mullen1200** [comment]
I've reinstalled the latest miner, deleted the stats files, restarted my computer, and restarted it multiple times. I tried launching zminer 130+ times last night. I'm pretty sure I'm stuck.

I've also been sometimes getting "no pools" error when starting. I suspected I had some sort of network issue, but its hard to nail down since its only happened like 3 times.

**Comment by Sniffdog** [comment]
...looking at other options...

Nopool sometimes means that miningpoolhub api was down.... I have never changed EWBF Zminer since it was included

**Comment by Sniffdog** [comment]
not getting errors here or can reproduce what happening to you... have you tried excavator in Sniffdog?

...just looking at all your options

**Comment by Sniffdog** [comment]
ok one more question... was Zminer trying to mine Bitcoingold?

**Comment by mullen1200** [comment]
It stops at 

   Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-EWBF\Zminer.exe --api --server  --port  --fee 0 --solver 0
                                               --eexit 1 --user  --pass

**Comment by Sniffdog** [comment]
that's an api issue with equihash...

I'm gonna add https://github.com/poolgold/ewbf-miner-btg-edition/releases and place it in the bin I'll be done shortly

**Comment by Sniffdog** [comment]
ok it's done until ewbf 0.3.4c comes out

Here is
![screenshot 10](https://user-images.githubusercontent.com/30452757/34691578-39f2c876-f47a-11e7-82e2-3b602a9c8b87.png)
 what I'm getting...

**Comment by Sniffdog** [comment]
![screenshot 12](https://user-images.githubusercontent.com/30452757/34691918-789bbdb6-f47b-11e7-9e6d-3908f3de9f01.png)

this is it benching

**Comment by Sniffdog** [comment]
Have modified the EWBF to unpack properly in Sniffdog... I'll add it in the next release
