### ISSUE TITLE
You all getting tired of Sniffdog? 

### ISSUE THREAD

**Issue by Sniffdog** [Sniffdog/Sniffdogminer#59]
Hashsynminer has been released!

Happy Mining!

**Comment by YagerD** [comment]
What is the upside to Hashsynminer vs sniffdog?  I have been working on tweaking sniffdogminer but its had to get a solid benchmark when mining to different pools.  Do you know of any write ups explaining how to read the hashrate charts on these different pools to understand if a specific algorithm is worth running on that pool and if the auto difficulty setting is putting you in a the sweet spot for mining?  Having a hard time finding much information about these topics.

**Comment by Sniffdog** [comment]
That is why we leave it to the individual...(here comes a metaphor) lol

It's like being in room at a certain temperature.... half the people find the temperature to be to hot.... while the other half feels like the room is to cold....

If we actually mention a proper setting for a particular algo... there will always be others that will disagree..

**Comment by YagerD** [comment]
Ya I completely agree all settings are different even for the "same" cards. I'm not looking for a someone to tell me a specific number for difficulty, or interval times, algo's for certain pools, etc.  I'm just trying to learn as much as I can and it seems for multi algo switching / pool switching miners, being able to decipher information from logs and pool graphs is vital.

**Comment by Sniffdog** [comment]
All I can say is try it out when you have time (and I mean a lot of time... there is a lot of unpacking and setting up for Hashsynminer if your going to individual cards)... tested on a 6 card rig....right now I have two clients so only have this particular rig split in half equally after the testing (3 each) so I only needed two strings of the hashsynminer_start.bat

**Comment by spacebarrier** [comment]
I'm having problems getting it to work - Can someone help me ?

I've been mining zcash for quite some time now, but wanted to check this out - The problem is, I'm not receiving anything, so I guess that I made some mistake while setting it up. Also, I'm not seeing my worker on multipool, nor have I received anything on my wallet.

Cheers

![screen shot 2018-01-15 at 10 01 03 am](https://user-images.githubusercontent.com/31069504/34934592-4d549050-f9db-11e7-8077-b0f0aff23362.png)

**Comment by kingyem** [comment]
Would you mind posting your command line?

**Comment by spacebarrier** [comment]
Sure, just tell me what exactly to post.

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Username space -Workername worker1 -RigName space.rig -Currency USD -Passwordcurrency BTC -interval 90 -Delay 1 -Wallet 1PyAgUR7ZR6DPgF8KupeYfGX6WeFHS3vVn -Location US -PoolName zpool,Hashrefinery,MPH,ahashpool -Type nvidia,cpu -Algorithm phi,hsr,xevan,tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,lyra2z,timetravel,polytimos,ethash,yescrypt,m7m -Donate 5

![screen shot 2018-01-15 at 10 30 29 am](https://user-images.githubusercontent.com/31069504/34935875-a827c4e4-f9df-11e7-8b5c-15fe067a58e5.png)
![screen shot 2018-01-15 at 10 33 17 am](https://user-images.githubusercontent.com/31069504/34935876-a8409122-f9df-11e7-93ec-29e0e18e6bee.png)

**Comment by kingyem** [comment]
What's the longest time period you have let the miner run without any change in your balance?

**Comment by spacebarrier** [comment]
12h exactly, since last last night - Woke up this morning, and found nothing, so yeah .. Any ideas ? Should I be seeing worker on multipool, and if so, how long after I started miner ?

**Comment by Sniffdog** [comment]
@spacebarrier i need more info..screenshot of sniffdog running and your startsniffin.bat(without your info or course)

@kingyem not sure what you are saying... hopefully you can see sniffdog working at the pool wallets..

**Comment by kingyem** [comment]
@Sniffdog was asking for more info for the issue he is having :) at the start of the conversation, no info was presented

myself, everything is working fine
