### ISSUE TITLE
Monitoring miners

### ISSUE THREAD

**Issue by elf1ua** [Sniffdog/Sniffdogminer#6]
In the middle of the night all miners stopped working. There was only main window, but none of miners were running (6x1080Ti rig).
Solution for monitoring miners is a must. (BTW, nicehash do have it and reload the miner in case of zero hashrate, gpu falling or stuck miner)

**Comment by Sniffdog** [comment]
yes thats why at hashrefinery there is ethmonitoring if you wish to monitor. I think it's two bucks a month. Also, a beta program to reboot your computer..

Personally I setup task manager to reboot while I sleep daily and place startsniff.bat into startup... also set bios to auto in case of power outages. On top of that I also have a  wall plug that i can turn my rig on and off with my cell phone. Very handy for programs that freeze (it does happen).

Hope this helps you in keeping your miner operating properly. I do try to keep Sniffdog as simple and "light-end" as possible...

**Comment by superyoung83** [comment]
You can also write a simple script which kills all the miner tasks including the main window and relaunches startsniffin once an hour to reduce. downtime.
