### ISSUE TITLE
Benchmark values should be updated

### ISSUE THREAD

**Issue by meyerbro** [Sniffdog/Sniffdogminer#62]
Hi guys, first, thanks for this great project!

Second, would it be possible that the benchmark values get updated also during the day to day?

I'm saying this because it's very common for me to see different values from the current hash rate (higher) and the one that was saved with the benchmark.

If this is not consistent between the algos we have problems because the software will select the wrong profitability.

Thanks

**Comment by Sniffdog** [comment]
Non of these miners are perfect... they auto bench all the time...

Tip that I heard to try: after initial benching is complete... make the hashrates in stats folder (read only)

**Comment by meyerbro** [comment]
Are you sure?

My X17 is at 36 since it benchmarked and never changed... And my files are not read-only...

**Comment by meyerbro** [comment]
<img width="608" alt="screenshot 2018-01-09 19 41 54" src="https://user-images.githubusercontent.com/1686520/34739744-2c167ac6-f575-11e7-95b4-31a5e674ffd8.png">
Also, is this even possible? $150 with 3 1080 TI?

**Comment by Sniffdog** [comment]
haha no that is the movement as to which I speak of....at one time zpool used to lead the pack over all other pools... now others have caught on how to drive hashing to their sites...

I mean honestly... how can one site be so different than other if its the same coin??

...just a different perspective perhaps..

oh btw... and yes if you look at the logs in stats folder you will see how it fluctuates over (and upto) a weekly period

**Comment by YagerD** [comment]
"Tip that I heard to try: after initial benching is complete... make the hashrates in stats folder (read only)"
I'm gonna give this a try and see what I come up with.

**Comment by Sniffdog** [comment]
ok just make sure they are perfectly benchmarked :)

**Comment by YagerD** [comment]
Will do.  I will compare some logs later tonight or tomorrow.

**Comment by meyerbro** [comment]
Thanks!

**Comment by kingyem** [comment]
1 observation I just noticed, benchmarking time frame follows the time interval for refresh, so assuming you put the interval low, your benchmark results might not reach its highest potential. try to change your interval to longer when benching, it will take a lot longer to finish but i think this will solve the mismatch between current rates to benchmarked.
