### ISSUE TITLE
Worker name not used

### ISSUE THREAD

**Issue by joeyoon80** [Sniffdog/Sniffdogminer#63]
Hi. Just want to ask, previously when I was using v3.2, it recognizes the worker name in my .bat file. The latest v3.5 doesnt and automatically changes it to Sniffdog.

![sniffdog issue](https://user-images.githubusercontent.com/32901879/34764817-a851117c-f62a-11e7-946c-d422c9f517aa.JPG)

**Comment by Sniffdog** [comment]
no in the read.mde file -RigName is now the name of your rig....
