### ISSUE TITLE
Ccminer(V3.5) Stoped working while benchmark Algo X17 

### ISSUE THREAD

**Issue by soulofspirit** [Sniffdog/Sniffdogminer#64]
Hi, I had installed 1080ti  8slots on rig and got sniffdogminer_V3.5

while benchmarking Algorithm : X17   the ccminer was stoped like this pic. 

![3 5_x17 stop working2](https://user-images.githubusercontent.com/35310067/34791928-09e67c9e-f679-11e7-8922-27d88e7c870d.png)

How to configure this error.
Thx

**Comment by Sniffdog** [comment]
turn off your overclocking?... or turn intensity down in the Miners Folder (Ccmineralexis.ps1) "right click and EDIT"

**Comment by soulofspirit** [comment]
Same error after turn off oc....

Should try to adjust virtual memory?

**Comment by Sniffdog** [comment]
yeah optimal is 64k

**Comment by BMR79** [comment]
I see now on the pool name, instead of stating after the pool (unknown) it now states a number - coins. What is this refering to? Is it dual mining?

**Comment by Sniffdog** [comment]
What it means is... There is that many coins on that particular algo the pool selects which coin is being mined

**Comment by soulofspirit** [comment]
While algorithm is swapping... some GPU doesn't work around 1-5 min. Is this normally case?  


![untitled](https://user-images.githubusercontent.com/35310067/34932858-31f4290c-fa07-11e7-8821-8df25a422e39.png)

**Comment by Sniffdog** [comment]
some are reporting alexis not working at all with rigs over 4 gpu 1080 rigs...

I know on my rigs... it usually takes about a minute for all of the rig to get started
