### ISSUE TITLE
"Writing web request" stuck on main summary screen

### ISSUE THREAD

**Issue by kingyem** [Sniffdog/Sniffdogminer#66]
Hello,

Kudos to Sniffdog for the miner, really am impressed by it.

I'm reporting that after awhile of leaving my miner, there exists 3 "Writing web request" lines on the main summary screen, restarting the miner eliminates the lines. I would also like to note, that the "Writing web request" process happens every time i start the ahashpool.bat file.
![writingwebrequest](https://user-images.githubusercontent.com/35198970/34809413-cc867c6c-f6cf-11e7-8bb6-a417e01c5954.png)

**Comment by Sniffdog** [comment]
Can you let me know what is constantly downloading in the Bin folder.... usually it will appear then disappear...

**Comment by kingyem** [comment]
The only updated folder is the Excavator folder, and weirdly the folder became empty. I remember that I did move the proper files into the folder after downloading it.

**Comment by Sniffdog** [comment]
did you move all files it back one folder?

**Comment by Sniffdog** [comment]
Excavator\excavator.exe

When Excavator unpacks you will see  Excavator\excavator\excavator.exe.... you need to move all the files back one folder...

or else it will try to keep on downloading....

**Comment by Sniffdog** [comment]
![screenshot 14](https://user-images.githubusercontent.com/30452757/34810126-b87e0bdc-f656-11e7-9bff-257037fd50b7.png)
![screenshot 15](https://user-images.githubusercontent.com/30452757/34810131-bc6621bc-f656-11e7-9cfc-dafd5ade6fd1.png)
![screenshot 16](https://user-images.githubusercontent.com/30452757/34810136-bfbe064a-f656-11e7-82d4-6d50e22db166.png)

**Comment by kingyem** [comment]
Noted, will do this when I get back, kudos

**Comment by kingyem** [comment]
alright done as instructed and now the process doesn't happen, thank you for the swift reply
