### ISSUE TITLE
How do i change claymore to ethereum mining only mode?

### ISSUE THREAD

**Issue by kitty33421** [Sniffdog/Sniffdogminer#67]
I try to change config file but it dosen't work

**Comment by Sniffdog** [comment]
I left the readme!! file in the  claymore folder for you... just goto the miners folder and edit Duel_Ethash_Sia.ps1

Not sure where you are taking me with this question since miningpoolhub like nvidia with Siacoin....

**Comment by kitty33421** [comment]
Ok Thank you for your reply. I try to edit Duel_Ethash_Sia.ps1 by add commmand -mode 1 it's work.
The reason that I want to mine only ethereum because sia coin can't exchange to btc

**Comment by Sniffdog** [comment]
Thank you I did not know... much appreciated
