### ISSUE TITLE
Can I use both CPU & NVIDIA run together in one starisniff.bat ?

### ISSUE THREAD

**Issue by kitty33421** [Sniffdog/Sniffdogminer#68]
Can I use both CPU & NVIDIA run together in one starisniff.bat by edit type NVIDIA,CPU ?

**Comment by Sniffdog** [comment]
yup! run though on intel cpu

**Comment by kitty33421** [comment]
![capture](https://user-images.githubusercontent.com/35326109/34864484-1960ccae-f7a7-11e7-856d-5e86dbf43a44.PNG)
why It's appear only nvdia on screen like this?

**Comment by Sniffdog** [comment]
well reason is because I don't think MPH has a cpu coin unless you want to open up a algo to suit one of the algo's listed...

Make sure you add to each unpacked Ccminers both MSVCR120.dll and VCRUNTIME140.DLL...not all come with these files...

**Comment by Sniffdog** [comment]
![screenshot 17](https://user-images.githubusercontent.com/30452757/34864675-a97c4540-f732-11e7-97cb-5c102b873d6a.png)

**Comment by kitty33421** [comment]
ok I see I try to many algo but it dosen't work with intel cpu.Also I notice the sniff dog wasn't download JayDDeecpu miner on bin folder too.

**Comment by Sniffdog** [comment]
ah maybe you have an older version of sniffdog...  New release has Startsniffin.bat downloading JayDDee

**Comment by kitty33421** [comment]
I use sniffdog ver 3.6 and I just try add yesscrypt but it still the same

**Comment by Sniffdog** [comment]
yescrypt

**Comment by kitty33421** [comment]
![capture](https://user-images.githubusercontent.com/35326109/34865115-144bf786-f7aa-11e7-9525-0092ca7b7ed4.PNG)
yes I edit startsnif.bat look like this but cpu dosn't work

**Comment by Sniffdog** [comment]
ok... I'll download 3.6 and see on my testminer

**Comment by kitty33421** [comment]
Thank you I'm aprreciate it ^-^

**Comment by Sniffdog** [comment]
no problem I'll even use your algos and bench at MPH

**Comment by kitty33421** [comment]
Thank you sir

**Comment by Sniffdog** [comment]
no problem
