### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by pike1181** [Sniffdog/Sniffdogminer#69]
So I'm getting unreal results with my hashrates unlike any other miner out there. Super exciting!!!

But take this for example:
Ccmineralexis  Skein           1.94 GH/s 0.00400    0.00206  53.780
According to that it says at 1.94GHs should make me $53 a day, however when I plug that hash rate into coinwarz or whattomine I only get approx. $8 a day.
Please help me understand where and how the numbers for the estimated profits are generated in sniff dog miner.

I just started running this miner to test it's benchmarks and results.
I'm stunned by the output, but the average of them seem to be quite off from the results in my wallet. 

Thanks!

**Comment by mullen1200** [comment]
I had trouble with neoscrypt generating profit estimations off the chart. I had to rebenchmark twice (My computer was idle, only benchmarking)

**Comment by Sniffdog** [comment]
#37 @pike1181 

@mullen1200 if it corrected itself... then its a pool API or the pool's API to the exchange

**Comment by pike1181** [comment]
I'm running 2 x 1080TI's with cuda 9.1, driver 390.65 
I'll re-run the benchmarks but almost 50% of the estimations are off the charts.
I ran the original benchmark with the rig idle and stock GPU config. As SD started mining, I was able to OC about +100 to my core and +100 to my MEM without throwing any errors. anything higher tossed errors which was expected since SD doesn't like OC.

Here are what they look like right now:

CcminerKlaust  NeoScrypt     Benchmarking Benchmarking    0.49322 Benchmarking ahashpool-Unknown
Ccmineralexis  X17           Benchmarking Benchmarking    0.05931 Benchmarking ahashpool-Unknown
Ccminerpalgin  Xevan         Benchmarking Benchmarking    0.10949 Benchmarking ahashpool-Unknown
CcminerTpruvot Tribus        Benchmarking Benchmarking    0.00863 Benchmarking ahashpool-Unknown
CcminerTpruvot Phi           Benchmarking Benchmarking    0.03304 Benchmarking ahashpool-Unknown
Ccmineralexis  MyriadGroestl Benchmarking Benchmarking    0.00065 Benchmarking ahashpool-Unknown
Ccmineralexis  Lbry          Benchmarking Benchmarking    0.00081 Benchmarking ahashpool-Unknown
Ccmineralexis  Nist5         Benchmarking Benchmarking    0.01106 Benchmarking ahashpool-Unknown
Ccmineralexis  Skein         Benchmarking Benchmarking    0.00083 Benchmarking ahashpool-Unknown
Ccmineralexis  Sib           Benchmarking Benchmarking    0.02767 Benchmarking ahashpool-Unknown

And here's the output when actually mining:
Miner          Algorithm           Speed BTC/Day BTC/GH/Day USD/Day Pool
-----          ---------           ----- ------- ---------- ------- ----
Ccmineralexis  Skein           1.94 GH/s 0.00658    0.00339  90.008 ahashpool-Unknown
Ccmineralexis  Nist5         167.61 MH/s 0.00270    0.01610  36.932 ahashpool-Unknown
CcminerTpruvot Phi            60.90 MH/s 0.00232    0.03812  31.772 ahashpool-Unknown
Ccmineralexis  X17            34.54 MH/s 0.00191    0.05544  26.208 ahashpool-Unknown
CcminerKlaust  NeoScrypt       3.01 MH/s 0.00154    0.51283  21.130 ahashpool-Unknown
Ccmineralexis  Sib            40.57 MH/s 0.00141    0.03487  19.359 ahashpool-Unknown
Ccminerpalgin  Lyra2RE2      130.37 MH/s 0.00125    0.00957  17.075 ahashpool-Unknown
Ccminerpalgin  Xevan          11.09 MH/s 0.00101    0.09122  13.840 ahashpool-Unknown
CcminerTpruvot Tribus        199.28 MH/s 0.00075    0.00375  10.227 ahashpool-Unknown
CcminerKlaust  Groestl       134.17 MH/s 0.00074    0.00549  10.081 ahashpool-Unknown
Ccmineralexis  Blake2s        14.46 GH/s 0.00063    0.00004   8.634 ahashpool-Unknown
Ccmineralexis  Lbry            1.00 GH/s 0.00053    0.00053   7.272 ahashpool-Unknown
CcminerTpruvot Hsr            32.98 MH/s 0.00042    0.01269   5.728 ahashpool-Unknown
Ccmineralexis  MyriadGroestl 229.77 MH/s 0.00022    0.00096   3.019 ahashpool-Unknown

I'll re-post after next benchmark.

**Comment by pike1181** [comment]
Benchmark re-ran on idle again and here are my current results.
Still look VERY over inflated for these cards. No other miner gives results near these. I would be happy miner if these results were anywhere near true. C'mon SniffDog, make it happen! lol


Miner          Algorithm            Speed      BTC/Day BTC/GH/Day      USD/Day Pool
-----          ---------            -----      ------- ----------      ------- ----
Ccmineralexis  Skein            2.01 GH/s      0.00441    0.00219       59.495 ahashpool-Unknown
CcminerTpruvot Tribus         199.85 MH/s      0.00283    0.01418       38.255 ahashpool-Unknown
Ccmineralexis  X17             35.74 MH/s      0.00252    0.07055       34.033 ahashpool-Unknown
CcminerTpruvot Phi             63.52 MH/s      0.00213    0.03358       28.795 ahashpool-Unknown
Ccmineralexis  Nist5          174.80 MH/s      0.00192    0.01101       25.980 ahashpool-Unknown
CcminerKlaust  NeoScrypt        3.02 MH/s      0.00186    0.61700       25.154 ahashpool-Unknown
Ccmineralexis  Sib             43.78 MH/s      0.00130    0.02961       17.501 ahashpool-Unknown
CcminerTpruvot Hsr             33.55 MH/s      0.00121    0.03605       16.325 ahashpool-Unknown
Ccminerpalgin  Lyra2RE2       136.01 MH/s      0.00118    0.00865       15.881 ahashpool-Unknown
Ccminerpalgin  Xevan           11.12 MH/s      0.00095    0.08570       12.868 ahashpool-Unknown
CcminerKlaust  Groestl        140.68 MH/s      0.00087    0.00615       11.679 ahashpool-Unknown
Ccmineralexis  Lbry             1.05 GH/s      0.00054    0.00052        7.348 ahashpool-Unknown
Ccmineralexis  MyriadGroestl  246.64 MH/s      0.00019    0.00078        2.597 ahashpool-Unknown
Ccmineralexis  Blake2s       Benchmarking Benchmarking    0.00008 Benchmarking ahashpool-Unknown

**Comment by pike1181** [comment]
Thanks for the updates and quick responses. 5* on the support. Will send some crypto change your way once I see some profit come in. Awesome work brother.
