### ISSUE TITLE
Some suggestion for enhancement... 

### ISSUE THREAD

**Issue by farid93** [Sniffdog/Sniffdogminer#7]
Hi @Sniffdog ,

I like to request for adding this setting in sniffdogminer and it will help for those who are share mining rig with different GPU/VGA and for those are unable to connect to pool with standard connection?

>   -x, --proxy=[PROTOCOL://]HOST[:PORT]  connect through a proxy
> 
>   -d, --devices         gives a comma separated list of CUDA device IDs
>                         to operate on. Device IDs start counting from 0!
>                         Alternatively give string names of your card like
>                         gtx780ti or gt640#2 (matching 2nd gt640 in the PC).

The setting above pickup form ccminer.

Thanks.

**Comment by Sniffdog** [comment]
No problem... first of all splitsniff is out to choose your -d function :)

Second.... if you set your -Workername to your card model in miningpoolhub then you can use it for zpool and hashrefinery cause -Workername shows up as identification (ID=) in zpool and hashrefinery
