### ISSUE TITLE
Can't pass benchmark for JayDdee cpu miner ?

### ISSUE THREAD

**Issue by kitty33421** [Sniffdog/Sniffdogminer#71]
After I try to run JAyDdee cpu miner for many algorithm then sill benchmark only yescrypt  but no benchmark for other algoithm as picture
![capture](https://user-images.githubusercontent.com/35326109/34903538-36e86d3a-f866-11e7-9b41-cd08ef4b8cf0.PNG)

**Comment by Sniffdog** [comment]
I believe the only one is yescrypt in Miningpoolhub the others will be to difficult to mine with cpuminer

**Comment by kitty33421** [comment]
ok thank you ^_^

**Comment by kitty33421** [comment]
![capture](https://user-images.githubusercontent.com/35326109/34906135-6c5702d2-f899-11e7-9f57-ada458ac1811.PNG)
I try to increase interval up to 500 but it still the same. It continue to run on some algorithm other than yescrypt eg myr-gr

**Comment by Sniffdog** [comment]
well... if you really want to mine those other algo's ... it's upto you.... we just use cpuminer for yescrypt and m7m for now
