### ISSUE TITLE
Problems with sniffdog and MPH balance?!

### ISSUE THREAD

**Issue by ebojali** [Sniffdog/Sniffdogminer#74]
I've started my mining last night with sniffdog miner and after the becnhmarking was done it started to mine on equihash algo (Zclassic) but what I noticed today is that my balance sheet in MPH is empty. Is there anything that is setup wrongly in the sniffdog bat? I have autoexchange on to LTC on everything in MPH, also configured my exodus LTC mining wallet address in MPH for transactions and put the same in the sniffdog bat file.

This is how the edited bat looks like:

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Username rig1 -Workername DBminer -RigName rig1 -Currency EUR -Passwordcurrency LTC -interval 90 -Delay 1 -Wallet LUHS2KfP9YxqD1YRvR9JFnmhQEeBG1rjgX -Location europe -PoolName zpool,Hashrefinery,MPH,ahashpool -Type nvidia,cpu -Algorithm Skein,Equihash,Groestl,MyriadGroestl,Lyra2RE2,neoscrypt,lyra2z,ethash,Cryptonight -Donate 5

Please help!

Thanks
//Bojan

**Comment by ebojali** [comment]
Additional info, I tried single mining Zclassic with nheqminer and I can see it updates my balances accordinly. something must be wrong with my config for sniffdog? 

Coin | Normal Wallet | Auto Exchange Wallet | On Exchange |  
-- | -- | -- | -- | --
Zclassic | 0 | 0 (0.00004926) | 0 | Manage Wallet

**Comment by Sniffdog** [comment]
at miningppolhub if your -username and -workername (profile created at)are the same as your bat file you should have been mining just fine there.. That's all the requirements they need... also password should be x at miningpoolhub..... workername.x 

You must be mining at Zpool cause I believe he is paying out in LTC

I'm noticing europe in the bat file... so you are only mining at miningpool hub then.... you need to configure in miningpoolhub your coin exchange to LTC... all the rest of the pools SniffDog has are in the US

**Comment by ebojali** [comment]
Thanks alot for the fast reply
I changed to x now, it gave me the command:
 NVIDIA-EWBF\miner.exe --api --server europe.equihash-hub.miningpoolhub.com --port 17023 --fee 0 --solver 0 --eexit 1 --user rig1.DBminer --pass x

But I think the --user is worng order in the command since I've configured the following hub worker details. 
![image](https://user-images.githubusercontent.com/35561346/35097303-db3c6656-fc4f-11e7-9924-5f89a9aef9f2.png)

**Comment by Sniffdog** [comment]
yeah you got username and workername backwards in the startsniffin.bat

**Comment by ebojali** [comment]
Ok, I've changed that now and it seems to be working, I'll wait a bit and provide you some feedback. 
According to mininbpool hub multi algo switching should use port 12XXX but instead teh bat file seems to start algo switching towards 17XXX, is that correct?

Algo switch mining (Port 17XXX)
We provide auto switching port for each algo. These ports switch coins time to time to mine the most profitable coin. Best for Rental, ASIC, FPGA miners.

Multi-algo switch mining (Port 12XXX)
You can mine different algo coins by using Hub feature, or third party mining helper programs. Good for GPU miners but need some knowledge to set up and optimize.

https://miningpoolhub.com/index.php?page=gettingstarted

**Comment by Sniffdog** [comment]
No your fine and sorry for the late reply... your on the right ports

**Comment by ebojali** [comment]
thanks alot for all the great replies! I now relize what the different ports are for.
