### ISSUE TITLE
You will see red writing with hsrminer at ahashpool... this is normal....

### ISSUE THREAD

**Issue by Sniffdog** [Sniffdog/Sniffdogminer#75]
For some reason the Wrapper (pop up blue screen) gets stuck at ahashpool and does not produce a Wrapper_.txt file with a hashrate number for hsrminer.....

So you will see red writing that will say... "cannot find Wrapper_txt" 

This is not hurting Sniffdog... ( i have ran tests for almost a week ) without crashes or freezes...

We will continue updating once hsrminer(beta) (or another miner) improves performance for neoscrypt.

Hopefully, this will shed some light, as to why only nemominer and Sniffdog have this miner working.

I will today make a proper unpack of hsrminer with the right .dll files so everyone can run the start_for_benching_hsrminer_neo.bat first thing before running any other startsniffin.bat files

**Comment by Sniffdog** [comment]
Looks like nemominer is not adding hasrminer-neo... this is the only one that has it

**Comment by nemosminer** [comment]
yip ! for now
