### ISSUE TITLE
hsrminer . , fault?

### ISSUE THREAD

**Issue by aKra-NL** [Sniffdog/Sniffdogminer#76]
I'm doing like say 1234.56 kH/s and Sniffdogminer identifies this from the API as 123,40MH/s.

Might be a little error in the code ;)

Could be either with ., or kH/s instead of KH/s.

I'm not familiair with Powershell, so just calling the bug :)

**Comment by Sniffdog** [comment]
I used to get that to until I used the .bat file designed to bench the hsrminer.... you will find it in the lastest update  	start_for_benching_hsrminer_neo.bat

I first run this bat to bench hsrminer before moving onto the main startsniffin.bat file

**Comment by aKra-NL** [comment]
Let me check this, fresh git clone and first running your bat without editing it!

**Comment by aKra-NL** [comment]
Nope, still giving incorrect hashrate.

`Ccminer_hsrminer_neo NeoScrypt 340,56 MH/s 0,10963    0,32191 1.237,273 Hashrefinery-10-coin(s)`

**Comment by Sniffdog** [comment]
ok thanks... before the night is out... if this can't be fixed... I shall remove it

**Comment by aKra-NL** [comment]
I'm looking into it, but I'm not really familiair with Powershell, it might be the "[Math]::Pow(1000, 2)}" calculation and the fact that Powershell is not case sensitive, so the lines:
`
                "KH/s" {$HashRate *= [Math]::Pow(1000, 1)}
                "mH/s" {$HashRate *= [Math]::Pow(1000, 2)}
                "MH/s" {$HashRate *= [Math]::Pow(1000, 2)}
`
Might need to change?

**Comment by Sniffdog** [comment]
yeah it might be but still doesn't explain how my testminer is not picking this up anymore and your is???

**Comment by aKra-NL** [comment]
Just cloned the current release.

**Comment by Sniffdog** [comment]
I'll show my Wrapper_.txt number with 1080 and 1070 hashing

2125480.00

**Comment by aKra-NL** [comment]
Almost impossible to check since it gets removed by the Wrapper.ps.

**Comment by aKra-NL** [comment]
>     "Live":  359316000,
>     "Minute":  359316000,
>     "Minute_Fluctuation":  0.5,
>     "Minute_5":  359316000,
>     "Minute_5_Fluctuation":  0.5,
>     "Minute_10":  359316000,
>     "Minute_10_Fluctuation":  0.5,
>     "Hour":  359316000,
>     "Hour_Fluctuation":  0.5,
>     "Day":  359316000,
>     "Day_Fluctuation":  0.5,
>     "Week":  359316000,
>     "Week_Fluctuation":  0.5,
>     "Updated":  "\/Date(1516330811549)\/"

**Comment by Sniffdog** [comment]
shows up for just a moment... 

yup your not getting those two zero's removed from the end

**Comment by aKra-NL** [comment]
"KH/s" {$HashRate *= [Math]::Pow(1000, 1)}
"mH/s" {$HashRate *= [Math]::Pow(1000, 2)}
"MH/s" {$HashRate *= [Math]::Pow(1000, 2)}

?

**Comment by aKra-NL** [comment]
Add me on Skype: akra_teh

**Comment by aKra-NL** [comment]
And a few hours in, looking at a lot of code I found out it has to do with the Windows location settings. I had my Windows set on default Dutch (ugh). Since we use the "," as a financial separator and the US of A.... uses the "."... Since the hsrminer uses a "." the Powershell operator used uses these financial separators as a indication where to do the maths for kH/s untill pH/s.

So we need to find another operator in Powershell to do this without being dependent on system language.

Problem semi-solved.

**Comment by nemosminer** [comment]
tryed all of this my self... good luck hope you get it sorted if you need any help 
please PM me on BitcoinTalk  @minerx117

**Comment by Sniffdog** [comment]
yeah we left hsrminer in Sniffdog but also agreed to let this miner stay dormant for now....

For those wishing to still use hsrminer will have to reopen the algo  in miners folder and bench at either zpool or hashrefinery...

Note: this miner is made for the U.S. so you will need to change your Windows to English US settings to get hsrminer to work for you...
