### ISSUE TITLE
New miner

### ISSUE THREAD

**Issue by z4nik** [Sniffdog/Sniffdogminer#77]
Is it possible to add miner to the phi algorithm. On the test he gives more hashes. https://github.com/216k155/ccminer-phi-anxmod/releases

**Comment by Sniffdog** [comment]
Ok, I'll check it out no problem

**Comment by Sniffdog** [comment]
Looks good and unpacks... I'll place it into the Miners Folder 

Thanks!

**Comment by nemosminer** [comment]
caution with this miner i will be testing (and virus checking) today and report back... nemosminer/NemosMiner-v2.4#189
