### ISSUE TITLE
CcminerPhi does not work

### ISSUE THREAD

**Issue by z4nik** [Sniffdog/Sniffdogminer#78]
CcminerPhi fails to start with error the file Include.ps1

**Comment by aKra-NL** [comment]
Can you elaborate the error?

**Comment by Sniffdog** [comment]
yes please edit in miners folder Ccminerphi1.0.ps1 and change from API = "Wrapper" to API = "Ccminer"

I repaired this before before going to bed last night but didn't catch it before you downloaded... my apologies

**Comment by nemosminer** [comment]
caution with this miner i will be testing today and report back... https://github.com/nemosminer/NemosMiner-v2.4/issues/189

**Comment by Sniffdog** [comment]
yes we checked today with virustotal

Tpruvot(clean miner)

https://www.virustotal.com/#/file/f16f327c90455f200a18666e1e4ac138131b051f3d64825168bb7e3973a1a45d/detection

ccminerphi1.0

https://www.virustotal.com/#/file/30b6d58a01fd0e79d50371bd1bb184cb628e9a0422db3fb92105e69494eaf81e/detection
