### ISSUE TITLE
Include.psm1

### ISSUE THREAD

**Issue by chillware** [Sniffdog/Sniffdogminer#79]
the following error comes up after launch and every refresh during running using version 3.7

```
& : The specified module 'C:\Users\Miner2\Desktop\Sniffdogminer3.7\Sniffdogminer-master\Include.psm1' was not loaded
because no valid module file was found in any module directory.
At C:\Users\Miner2\Desktop\Sniffdogminer3.7\Sniffdogminer-master\Include.ps1:123 char:24
+            $Content = &$_.FullName
+                        ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Users\Miner2...er\Include.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by Sniffdog** [comment]
added into master files... thanks for the catch

**Comment by chillware** [comment]
Thx, added the file, works but after a bit the include.psm1 file disappears and the error returns. Is it getting deleted. same issue on 6 rigs.

**Comment by Sniffdog** [comment]
that is strange but still running tests here

**Comment by chillware** [comment]
Reboots seemed to have solved the issue.. very strange indeed. thanks though! Loving the script!

**Comment by Sniffdog** [comment]
Yeah I'm almost thinking I should do clean installs (applying Ccleaner and such) before newer version goes in
