### ISSUE TITLE
Issues with 4+ Rig Builds 1080ti

### ISSUE THREAD

**Issue by cryptomandingus** [Sniffdog/Sniffdogminer#80]
So I have a 6 card 1080ti rig (MSI), this rig has drivers 390.65 installed on to it. Not overclocking involved.  Everything works fine until the point when CCMiner starts when it runs for a couple of seconds/minute and then crashes resulting in it taking out one of my graphic cards, so that I have to restart the computer. The error I get changes depending on the miner running. This is not just an error I am getting as I found many other people experiencing the issue and none of them were able to find a solution to this issue. I tried turning down the intensity and not only did it kill my speeds but also the error still occurred just took a slight bit longer. This issue only arises when I go above 4 cards. Here is a gif of my error in action. Any help would be greatly appreciated.

https://gfycat.com/GlumGrossCavy

**Comment by aKra-NL** [comment]
Which ccminer? You could exclude that specific miner of being used. Or change it to the one you were using that does not give you any issues.

**Comment by cryptomandingus** [comment]
Firstly thanks for the quick response, 
no its all of them, that's why I stated "The error I get changes depending on the miner running" as the error is similar "CUDA: error in func 577", "CUDA kecak256_setblock_80". I can't even run miners not listed on snifferdog miner without it crashing.

**Comment by aKra-NL** [comment]
And you can run a single instance of 2.2.4-TPruvot without it being from the Sniffdogminer?

**Comment by gamer49** [comment]
Try running 4 cards as a test, and ensure isolation to the number of cards being run first. HB110 MB needs upgraded BIOS for multiple cards. There are various tuning/driver issues I've run into with 8 1080 cards on several mining software platforms nicehash non legacy, awesomeminer, sniffdog > 3.6. Also there are power issues to consider 1500 Watt max on a 15 amp circuit, and 2200 watts on a 20 amp circuit will affect stability at 120V. Then there's virtual memory memory requirements (just set a 64 gig virtual memory cache to avoid issues).  Obviously have not run into or tested most situations, just re-install drivers and go back to what worked before.  (No issues with sniffdog 2.8A and 390.65 drivers with 8 1080).

**Comment by cryptomandingus** [comment]
@aKra-NL  I can if it's less than 4 cards and has an extremely low intensity level for 5 cards

I was not trying to suggest that the issue was solely on snifferdog miner. I assume it was more likely an issue on the driver side or as you said the virtual memory, which I did turn up but still seemed to get little benefit from it. I actually only have 5 of the cards on one psu meaning that my power consumption is in the high 1300's so that isn't the issue. The suggestion I have not tested more situations honestly pains me, I have spent the last several+ hours uninstalling, reinstalling troubleshooting this issue. There never seems to be a clear answer as to why it occurs and the answers I have found don't seem to work. For example if you install Nvidia inspector you need to turn off the power switiching from the GPU from P2 to P0, did this help me, no. It has gotten to the point were I am going to have to test simplemining OS to see if a linux system causes the crashes to rule out if there is a hardware fault even though I highly doubt there is one. I am using Biostar TB-500 pro so its not a bios issue. I thank you for your suggestions but sadly I have tried a lot of them to know avail.

**Comment by Sniffdog** [comment]
just one question.... is your video output on that card that is crashing?

**Comment by cryptomandingus** [comment]
my video output quickly dies and comes back and I assume the card crashing happens in between (this particular issue is quite recent) but the card that dies in the gif is not the main display card, that card has yet to die with all of the tests. The video dropping out is a new pheneomon as orignally it would just go: 

Card Dies, Miner Brings Up Error Code, Miner Crashes, Card stays dead
Now it goes
Screen Flickers for a second, Miner brings up Error code, Card is already dead, Miner crashes, Card stays dead

**Comment by Sniffdog** [comment]
yeah I'm not familiar with biostar mobo we use Z270-a ASUS Prime for our rigs and they seem to be very stable. I tried to use and older Maximus VII mobo and had all kinds of issues similar to what you are describing..i got really tired of messing around with windows settings and mobo bios... so I turned it into a testminer with just two cards...

**Comment by Suyneej** [comment]
I made an account just to try and help you out. I recently just built two 6 rig 1080ti miners and had nothing but issues. In the end I ended up purchasing two asus b250 mining expert boards which seemed to alleviate all my issues, but I was able to have some success with my previous mobos.
-I would revert back to not forcing p0 power state, I noticed when I did that I had nothing but issues
-I also would try running 80% tdp and see if your issue persists
-Obviously update your bios if you haven't already
-On my 1st rig I initially had a 850w psu and a 1000w psu. I was having the same issues you where having and out of sheer frustration I changed out my 1000w PSU for two 750W PSU's. I was then runnning the cpu, 2x 1080tis and their respective risers off the 850 PSU, then one 750W PSU had the SSD, two 1080tis and their risers and the second 750W PSU I had the remaining GPUS and risers off it. Turned the rig on, ran sniffdog with 0 issues. So i believe it was a PSU issue...maybe this is your problem as well.

Now that I swapped both mobos to the b250s I kept the same PSU setup cuz I didnt want to deal with the headache so I cant say forsure if it was more the mobo or the PSU...either way hopefully this gives you some ideas. I was about ready to rip my hair out.

**Comment by cryptomandingus** [comment]
@Sniffdog 
well I haven't heard to many bad things about the board so I would not jump straight into thinking that it was the issue, but maybe it is and it would not surpise me if it was and as I say below to @suyneej if I can't get the cards to work with a different unbloated os then it could well be a hardware issue. 


@suyneej

Thanks man I really appreciate you making an account for this, so I weirdly I didn't seem to get more errors after the power switch to p0 but maybe it is causing something more under the hood that I could not see, I feel like I would literally put the whole rig underwater if it would somehow make it work just for more than 5 minutes. 

I had not tried running the cards at 80% tdp that is a suggestion I have not seen yet and I will give it a good go. 

I also though it could be a power issue, but this is were I am going to check after getting simpleminer to run. (Can't as the website severs are being odd) Because if I still can't get the cards to run on a OS made for mining and without the potentially damaging windows bloat wear, then the issue has to be a hardware and a software related so that would be the time to get out a new psu or something along those lines. I am really hoping it is not a Hardware issue as most shit is sold out right now due to high demand. 

I will report back tomorrow with any updates.

**Comment by Suyneej** [comment]
I should also mention, on my second mobo. I had to disable EVERYTHING I wasn't using. Built in WIFI, HD Audio, Enabled 4G decoding, Set PCI from auto to GEN 1 and PCIE speed from auto to 1x. I also had to disable all unused sata ports on my mobo. 
Its almost like one rig was a power issue, the other was a stability issue caused by lack of lanes. (both mobos were different, one was an asus x99 delux and the other was some AMD one i had laying around from 4 years ago)

**Comment by Sniffdog** [comment]
I understand... I will download right now SniffDog to my clients 6 1080ti rig that has a 1600w evga gold and a 1000 evgaG3

**Comment by cryptomandingus** [comment]
I have yet ot turn off the audio and onboard lan, which I heard could make a difference but I do not think that is what is causing my issue, my best guess is that my issue is caused by something more simple. Which is something to do with the virtual/actual memory of either my GPU's or windows Allocation. However my rig is in my office and I am at home so I cant tweak it any more this evening.

I would love to hear the results of that, because as I said earlier I have 5 cards on 1 1600w evga gold and 1 card on one 700w Chinese crud (as I am waiting for delivery of my other 1600w so I can add more cards as windows removed the Nvidia limit for cards (I heard).

Right I am off to bed (UK timezone GMT 0) I will hopefully have some answers later tomorrow.

**Comment by Sniffdog** [comment]
Honestly, I still have everything enabled... I just don't use overclock

**Comment by cryptomandingus** [comment]
Okay ao I did already try this and I still had the crash, after some testing with simpleminer (no bloatware) it seems that the issue has to be hard drive based as not only did one of my cards not read but then it feel of the board and crashed the program. Thanks for the help I will report if I find anything else out for people like me looking for a fix

**Comment by Sniffdog** [comment]
Thanks for your help too.... new update coming out shortly that might fix alexis.... dunno but worth a try...

**Comment by Sniffdog** [comment]
I'm also updating alexis hopefully fixes some things... Alexis always need intensity though....
