### ISSUE TITLE
NVIDIA-ALEXIS-78.zip downloading every interval

### ISSUE THREAD

**Issue by jayntguru** [Sniffdog/Sniffdogminer#83]
Running 3.8. It's downloading NVIDIA-ALEXIS-78.zip every time it runs an interval looks like.

**Comment by jayntguru** [comment]
Oh it's putting it one dir down.

F:\mine\Sniffdogminer3.8\Bin\NVIDIA-ALEXIS-78\NVIDIA-ALEXIS-78

**Comment by Sniffdog** [comment]
oh ok thanks I'll fix it

**Comment by Sniffdog** [comment]
try unpacking it now and let me know please :)

**Comment by jayntguru** [comment]
Grab latest? Or just re grab 3.8?

**Comment by Sniffdog** [comment]
you will probably have to grab latest... looks like this is not unpacking correctly
