### ISSUE TITLE
ccminer source codes? (GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007)

### ISSUE THREAD

**Issue by nemosminer** [Sniffdog/Sniffdogminer#86]
https://github.com/Sniffdog/Sniffdogminer/blob/master/LICENSE

Sniffdog/Sniffdogminer is licensed under the

GNU General Public License v3.0
Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

Reopen Issiue as Sniffdog Closed it : Closed Isssiue can be found here: https://github.com/Sniffdog/Sniffdogminer/issues/81

---------------------------------------------------------------------------
**_"@sniffdog quoted: You want me to add this all in?

Not sure why you are mentioning this... I don't change ccminer source codes

I can barely keep SniffDog going....

Please use your own thread for GNU topics... i would say 99% here don't give a crap

Anyone can fork and modify my freeware anytime they want to.... it's the same reason why crypto coins can be forked... to better the community and it's freedoms.

I'll be closing this now Nemo.... not impressed..."_**
------------------------------------------------------------------------------

It doesn't matter if you change them or not...

well sorry but i do  "give a crap" about Licences and GNU  you should to... 

You must provide source code for every ccminer you release so if people want to compile there own they can...  

im mentioning this because you had multiple ccminer downloads on your github that had no source code at all...   

Regards 
Nemo

**Comment by Sniffdog** [comment]
yes I was practicing... no harm no foul... just new at Github

**Comment by nemosminer** [comment]
sorry i am trying to help you...

**Comment by Sniffdog** [comment]
it's ok it's fixed now

**Comment by nemosminer** [comment]
You can close this Issue Now all is well : )
