### ISSUE TITLE
https://github.com/Sniffdog/Sniffdogminer/tree/master/Bin/NVIDIA-ALEXIS_78

### ISSUE THREAD

**Issue by nemosminer** [Sniffdog/Sniffdogminer#87]
Source Code?

**Comment by Sniffdog** [comment]
in the bin folder

**Comment by nemosminer** [comment]
there is no soucre code in the bin folder just executable file

here is the source code: https://github.com/nemosminer/ccminer-Alexis78

**Comment by Sniffdog** [comment]
so is hsrminer... so why were we working on thst together then?

**Comment by nemosminer** [comment]
we wernt

**Comment by Sniffdog** [comment]
oh yes you were...

**Comment by Sniffdog** [comment]
what about Sp... you gonna ask him for source code?

**Comment by nemosminer** [comment]
https://github.com/palginpav/hsrminer/raw/master/Neoscrypt%20algo/Windows/hsrminer_neoscrypt.exe





i don't keep PalginHsr on Git hub i download directly from source....

you just need to fork ccminers properly and do proper release or else just don't keep them on your git hub change your download urls to download from source

**Comment by nemosminer** [comment]
so is hsrminer... so why were we working on thst together then? because i wanted to see what you coding skills were like... i was not impressed are you 12 years old?

**Comment by Sniffdog** [comment]
hmmmm.... well he seems to make 100 or thousand of dollars doing it without a fuss... makes me even more curious as to why your interested in this one...

**Comment by nemosminer** [comment]
its not about money

**Comment by Sniffdog** [comment]
I'll need to research this miner further.... you have me very curious

**Comment by nemosminer** [comment]
HSRminer doesn't have a licence you can do what you like with it...  https://github.com/palginpav/hsrminer

**Comment by Sniffdog** [comment]
http://cryptomining-blog.com/8471-you-should-use-ccminer-alexis-1-0-for-better-x11-ghost-hashrate/

**Comment by nemosminer** [comment]
yip read the full post they have source code listed and available so people can compile there own

**Comment by nemosminer** [comment]
if you can't find where they list it...

" but you can get faster speeds on the same hardware by using the latest ccMiner fork from alexis 78 (source). We have compiled a 64-bit Windows binary with Compute 5.x support and CUDA 7.5 "

**Comment by nemosminer** [comment]
your digging yourself a hole here mate...

**Comment by nemosminer** [comment]
ok

**Comment by Sniffdog** [comment]
nice chatting to you Nemo...

**Comment by Sniffdog** [comment]
just saying... I'll compile it

**Comment by nemosminer** [comment]
heres the Original Source code...

: https://github.com/alexis78/ccminer

Alexis78 has never compile a Release since he wrote the Original code that is why me and other such as "http://cryptomining-blog.com" have compiled our own so people like you and me can use it... not my Release date was well before the "http://cryptomining-blog.com"  you have been referring to...

**Comment by Sniffdog** [comment]
there now mine is legit and has all respected parties included in read.txt and placed into Bin Folder.

**Comment by nemosminer** [comment]
You can close this Issue Now all is well : )
