### ISSUE TITLE
Not benchmarking newly added algos and no algo switch.

### ISSUE THREAD

**Issue by ebojali** [Sniffdog/Sniffdogminer#89]
Hi, 

I just added the below algorithm flag, so the new ones are X11,Scrypt,Yescrypt,Sia,Qubit which I would like to have benchmarked, but that newer happens when I start it up, any ideas? See picture below.
-Algorithm Skein,Equihash,Groestl,MyriadGroestl,Lyra2RE2,neoscrypt,lyra2z,ethash,Cryptonight,Keccak,X11,Scrypt,Yescrypt,Sia,Qubit 
![image](https://user-images.githubusercontent.com/35561346/35216467-0235b49a-ff68-11e7-82c5-98c465b7e702.png)

Additionally it seems like it doesn't choose the most profitable algo to mine when I start sniffdog miner, according to MPH it was equihash but it started to mine digibyte-skein.  See picture below

![image](https://user-images.githubusercontent.com/35561346/35216474-073f07c0-ff68-11e7-9823-7acf37774135.png)

**Comment by Sniffdog** [comment]
Did you check the API at miningpoolhub at that time... the link in the the pools folder for MPH.ps1.....

Also, there are reasons as to why I turn off algos's...if you want to open them...that's upto you.... Sia is also with ethash as a duel miner. I don't check those algo's to which have been closed

That's a very cool version of sniffdog too... mine doesn't have the dots...

**Comment by ebojali** [comment]
Sorry I'm kind of new to the mining concept, what do you want me to check in the API? I looked at the link in the MPH.ps1 and it gave me a hostlist of all the algorithm and what coins there are. 

You know where I can open up algos? :)

Cheers!

**Comment by Sniffdog** [comment]
ok thank you for letting me know your new at this....

Sniffdog picks up messages from each pool via a "API" that tells price..... (at the exact time Sniffdog calls for the check)... then figures out (from which of the pools)  the best algo to mine.... 

So these pools might show which is the highest algo to mine... but their API says(at the time Sniffdog call for a check) something different

**Comment by ebojali** [comment]
Ok,  I understand so there API would be when you query the API that would give the most accurate response  I guess while the webpage might have some delays for updating etc.. Is there anyway to enable other algos in the code? I wasn't able to find where you disabled algos. 

Thanks a lot for a nice application and great support!

**Comment by ebojali** [comment]
Btw, I noticed that the response from https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics (normalized profit nvidia) doesn't even come close to what is on the webpage. Wonder if this is a bug from their side...

**Comment by Sniffdog** [comment]
inside the miners folder... edit the files and you will see the algo's... to enable remove the # in front of the algo...

Not sure if it's a bug... but we do use Miningpoolhub as a backup pool in case of yiimp pool failure..... Miningpoolhub is a nomp pool.... all the rest are yiimp pools

**Comment by ebojali** [comment]
Thanks a lot. We can close this issue.
