### ISSUE TITLE
GPU #X: result does not validate on CPU! error on CCminer

### ISSUE THREAD

**Issue by nravanelli** [Sniffdog/Sniffdogminer#93]
Firstly great autoswitching miner! 

I think it might be nice to be able to select intensities so you can mitigate these issues... any chance of that being implemented or perhaps the miner auto-recognizes it is not doing something and restarts? I dunno, just a couple thoughts... thanks :)

**Comment by Sniffdog** [comment]
#88 

Also if you checkout hashrefinery home page there is a link to ethmonitor which you place in the background of your rig and monitor from an app

**Comment by nravanelli** [comment]
I had edited the miner files after digging a bit more, and I am definitely going to look into ethmonitor. It looks like a perfect solution for my 4 rigs.
