### ISSUE TITLE
out of memory  scanhash_cryptonight

### ISSUE THREAD

**Issue by ebojali** [Sniffdog/Sniffdogminer#98]
Hi,

I finally got my 6 1080 ti rig up and running, but when starting trying to benchmark it when I run sniffdog for the first time I get the folloing memory error.. When I set the intensity to "-i 10" in the CcminerTpruvot.ps1 for cryptonight it seems to be starting fine, see the two pictures below, but the hashrate is not quite right? Anything that you or anyone is aware off?

It worked fine when I tested it on defualt parameters but with 3 1080 ti cards. 

Not OK:
![image](https://user-images.githubusercontent.com/35561346/35379131-62fa1aba-01b5-11e8-883b-f3e816c36f32.png)

Changed intensity to 10

OK:
![image](https://user-images.githubusercontent.com/35561346/35379321-fa98de06-01b5-11e8-987b-ceb72f667e19.png)

Thanks!

**Comment by Sniffdog** [comment]
No thank you! Was there any other issues you in-countered? 

How was x11? Did you need to add any intensity for that?

**Comment by ebojali** [comment]
Not sure what you mean with no thank you.. :) I had to tweak X11 to get working as well:  X11 = ' --api-remote -i 21'. 
I am using latest releases from Nvidia, CUDA 9.1 and 390.65 driver. Perhaps this is not the right forum to ask since might be more of a miner problem than a snifdog issue. If that is the case I'm so sorry, I blame my competence level here since I have just started with cryptocurrency mining.

**Comment by ebojali** [comment]
btw: 
I see it has benchmarked it with speeds of 183.63 MH/s but it actually dissapeared from the summary printout:

Before: 
![image](https://user-images.githubusercontent.com/35561346/35393601-b798ad0e-01e5-11e8-8a1f-090764c710fe.png)

After:
![image](https://user-images.githubusercontent.com/35561346/35393628-d004f794-01e5-11e8-8be8-3dfbf32d5c32.png)

**Comment by Sniffdog** [comment]
Yes... if you don't get a share from that algo while it's benching.... SniffDog will remove it

You will either have to go longer on the benching(increase interval) in order for a chance to receive a share
