### ISSUE TITLE
Application has been blocked from accessing Graphics Hardware

### ISSUE THREAD

**Issue by seanklei10** [Sniffdog/Sniffdogminer#99]
I previously had 2x 1080TI's and a K4200 in my desktop. I have replaced the K4200 with another 1080TI( 3 total now). I went to rebenchmark and I'm now getting a windows message that says "Application has been blocked from accessing Graphics hardware. Application ccminer.exe has been blocked from accessing Graphics hardware" Any thoughts?

**Comment by Sniffdog** [comment]
there are many things that could be affecting this

Have you turned off SLI?

**Comment by seanklei10** [comment]
SLI seemed to be the issue, I removed the bridge and manually set cards 2 and 3 to PCIe 1x, all appears to be working. Thanks!
